-- ******************************* SqlDBM: Databricks *******************************
-- * Generated by SqlDBM: Databricks sample, v2 vs v1 by hazal.sener+yew@sqldbm.com *

ALTER TABLE Dim_Supplier
  SET TBLPROPERTIES (delta.columnMapping.mode = 'name', Type = 'Simple');
ALTER TABLE Dim_Supplier
  RENAME COLUMN CompanyName TO Company;