-- ****************************** SqlDBM: Databricks ******************************
-- * Generated by SqlDBM: Databricks Demo, v8 vs v7 by hazal.sener+yew@sqldbm.com *

ALTER TABLE retail_analytics.customer
  SET TBLPROPERTIES (delta.minWriterVersion = 7, delta.feature.appendOnly = 'supported', delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
ALTER TABLE retail_analytics.customer
  RENAME COLUMN first_name TO demo;