-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- **************************************  "COST CENTER"
CREATE TAG IF NOT EXISTS "COST CENTER" ALLOWED_VALUES 'finance', 'marketing';
