-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Project - Snowflake by hazal.sener@sqldbm.com *

-- **************************************  EDW.cost_center
CREATE TAG EDW.cost_center ALLOWED_VALUES 'val_1', 'val_2'
 COMMENT = 'cost center tag';
