-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Project - Snowflake by hazal.sener@sqldbm.com *

-- **************************************  HOTELBNB.Tag_2
CREATE TAG HOTELBNB.Tag_2 ALLOWED_VALUES 'val_3'
 COMMENT = 'demo';
