-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- **************************************  "INFOMART"."DOMAIN"
CREATE TAG IF NOT EXISTS "INFOMART"."DOMAIN" ALLOWED_VALUES 'SALES', 'SUPPLY CHAIN';
