-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- **************************************  "INFOMART"."PII"
CREATE TAG IF NOT EXISTS "INFOMART"."PII" ALLOWED_VALUES 'ADDRESS', 'EMAIL', 'NAME'
COMMENT = 'Flag for identifying PII sensitive Data';
