-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Awesome Project by hazal.sener@sqldbm.com ***

-- **************************************  TAG_SCHEMA.Issues
CREATE TAG TAG_SCHEMA.Issues;
