-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Project - Snowflake by hazal.sener@sqldbm.com *

-- **************************************  TAG_SCHEMA.Medallion
CREATE TAG TAG_SCHEMA.Medallion ALLOWED_VALUES 'Gold', 'Silver', 'Bronze';
