-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Project - Snowflake by hazal.sener@sqldbm.com *

-- **************************************  TAG_SCHEMA.Issues
CREATE TAG TAG_SCHEMA.Issues;
