-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Awesome Project by hazal.sener@sqldbm.com ***

-- **************************************  TAG_SCHEMA.Medallion
CREATE TAG TAG_SCHEMA.Medallion ALLOWED_VALUES 'Gold', 'Silver', 'Bronze';
