-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- **************************************  "TAG_3"
CREATE TAG IF NOT EXISTS "TAG_3" ALLOWED_VALUES '1', '2';
