-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "CALC_TOTAL_SALES"
CREATE PROCEDURE IF NOT EXISTS "CALC_TOTAL_SALES"-- Procedure: Calculate total sales for a given year
CREATE OR REPLACE PROCEDURE CALC_TOTAL_SALES(YEAR_PARAM INT)
RETURNS FLOAT
LANGUAGE JAVASCRIPT
AS
$$
    var sql_command = `
        SELECT SUM(TOTAL_SALES_AMT) AS TOTAL_SALES
        FROM FACT_SALES FS
        JOIN DIM_DATE D ON FS.SALE_DATE = D.DATE
        WHERE D.YEAR = :1
    `;
    
    var stmt = snowflake.createStatement({
        sqlText: sql_command,
        binds: [YEAR_PARAM]
    });
    
    var result = stmt.execute();
    result.next();
    return result.getColumnValue(1);  -- return total sales
$$;

-- Usage
CALL CALC_TOTAL_SALES(2024);
