-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Project - Snowflake by hazal.sener@sqldbm.com *

-- ************************************** HOTELBNB.SQL_PROCEDURE
CREATE PROCEDURE ADVENTUREWORKSDW.HOTELBNB.SQL_PROCEDURE()
  Returns string -- Please specify return type
  Language sql
  Comment = 'It is a nice procedure'

AS
$$
select 1
$$;
