-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "1_V"
CREATE VIEW IF NOT EXISTS "1_V"
(
  "DW_CREATED_TS",
  "CREATED_BY",
  "UPDTD_TS",
  "UPDTD_BY",
  "IS_UPDTD",
  "TEST" COMMENT 'test desc',
  "COL_7"
)
AS
CREATE VIEW SCHEMA_NAME.VIEW_NAME
(
	COLUMN_ONE,
	COLUMN_TWO,
	COLUMN_THREE
)
AS
SELECT
	t.COLUMN_ONE,
	t.COLUMN_TWO,
	t.COLUMN_THREE
FROM SOURCE_TABLE t;

