-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "INFOMART"."V_SALES_PERFORMANCE_BY_GEO_TIME"
CREATE VIEW IF NOT EXISTS "INFOMART"."V_SALES_PERFORMANCE_BY_GEO_TIME"
(
  "COUNTRY_NAME",
  "STATE_CD",
  "CITY_NAME",
  "YEAR",
  "QUARTER",
  "TOTAL_QUANTITY_SOLD",
  "TOTAL_SALES_AMOUNT"
)
AS
SELECT 
    G.COUNTRY_NAME,
    G.STATE_CD,
    G.CITY_NAME,
    D.YEAR,
    D.QUARTER,
    SUM(FS.SOLD_QTY) AS TOTAL_QUANTITY_SOLD,
    SUM(FS.TOTAL_SALES_AMT) AS TOTAL_SALES_AMOUNT
FROM 
    FACT_SALES FS
JOIN 
    DIM_GEOGRAPHY G ON FS.GEOGRAPHY_HKEY = G.GEOGRAPHY_HKEY
JOIN 
    DIM_DATE D ON FS.SALE_DATE = D.DATE
GROUP BY 
    G.COUNTRY_NAME,
    G.STATE_CD,
    G.CITY_NAME,
    D.YEAR,
    D.QUARTER;

