-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: test project by hazal.sener+yew@sqldbm.com **

-- ************************************** demo.retail_analytics.mv_daily_sale_summary
CREATE MATERIALIZED VIEW demo.retail_analytics.mv_daily_sale_summary 
AS
 SELECT
    sale_date,
    store_id,
    SUM(total_amount) AS total_sales,
    COUNT(*) AS transaction_count
FROM retail_analytics.sale
GROUP BY sale_date, store_id;
