-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: test project by hazal.sener+yew@sqldbm.com **

-- ************************************** demo.retail_analytics.mv_top_customer
CREATE MATERIALIZED VIEW demo.retail_analytics.mv_top_customer 
AS
 SELECT
    customer_id,
    SUM(total_amount) AS lifetime_value
FROM demo.retail_analytics.sale
GROUP BY customer_id;
