-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: test project by hazal.sener+yew@sqldbm.com **

-- ************************************** demo.serge.mv_customer
CREATE MATERIALIZED VIEW demo.serge.mv_customer 
COMMENT 'sample view by serge'
AS
 SELECT
    id,
    name,
    email,
    prefernce,
    age,
    balance,
    tags,
    address,
    preferences,
    preferences2,
    CASE
        WHEN age < 18  THEN 'Minor'
        WHEN age < 35  THEN 'Young Adult'
        WHEN age < 55  THEN 'Middle Aged'
        ELSE 'Senior'
    END AS age_group
FROM demo.serge.customer;
