-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "2"
CREATE TABLE IF NOT EXISTS "2"
(

);
