-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "4"
CREATE TABLE IF NOT EXISTS "4"
(

);
