-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "6"
CREATE TABLE IF NOT EXISTS "6"
(

);
