-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** agg_daily_sales
CREATE TABLE IF NOT EXISTS agg_daily_sales
(
 agg_id                    int NOT NULL CONSTRAINT pk_agg_daily_sales PRIMARY KEY,
 dt_id                     int NOT NULL,
 store_id                  int NOT NULL CONSTRAINT fk_agg_daily_store REFERENCES dim_store,
 product_category_id       int NOT NULL CONSTRAINT fk_agg_daily_category REFERENCES dim_product_category (category_id),
 total_sales_amt           decimal(15, 4) NOT NULL,
 total_quantity_sold       decimal(12, 4) NOT NULL,
 total_cost                decimal(15, 4) NOT NULL,
 total_profit              decimal(15, 4) NOT NULL,
 transaction_cnt           int NOT NULL,
 average_transaction_value decimal(15, 4),
 unique_customers          int
);
