-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** agg_monthly_supplier_performance
CREATE TABLE IF NOT EXISTS agg_monthly_supplier_performance
(
 agg_id                  int NOT NULL CONSTRAINT pk_agg_monthly_supplier_performance PRIMARY KEY,
 dt_id                   int NOT NULL CONSTRAINT fk_agg_monthly_dt REFERENCES dim_dt,
 supplier_id             int NOT NULL,
 total_purchase_amt      decimal(15, 4) NOT NULL,
 total_quantity_received decimal(12, 4) NOT NULL,
 on_time_delivery_cnt    int,
 total_orders            int,
 average_quality_score   decimal(3, 2)
);
