-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: test project by hazal.sener+yew@sqldbm.com **

-- ************************************** demo.andy.tournament_winning_events
CREATE TABLE demo.andy.tournament_winning_events
(
 value string
)
USING DELTA
 COMMENT 'Created by the file upload UI'
 TBLPROPERTIES (delta.parquet.compression.codec = 'zstd', spark.sql.statistics.version = 2, delta.minWriterVersion = 7, spark.sql.statistics.auxiliaryInfo = '{"source":"AUTO_STATS"}', spark.sql.statistics.colStats.value.createdBy = 'root', delta.feature.appendOnly = 'supported', spark.sql.statistics.colStats.value.rowCount = 30, spark.sql.statistics.colStats.value.distinctCount = 29, spark.sql.statistics.numRows = 30, spark.sql.statistics.colStats.value.avgLen = 41, spark.sql.statistics.colStats.value.maxLen = 77, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, spark.sql.statistics.colStats.value.version = 2, delta.checkpoint.writeStatsAsStruct = true, spark.sql.statistics.colStats.value.nullCount = 0, spark.sql.statistics.totalSize = 1249, spark.sql.statistics.createdAt = 1762467116971, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', spark.sql.statistics.colStats.value.createdAt = 1762467116971, spark.sql.statistics.createdBy = 'root', delta.feature.invariants = 'supported');
