-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: test project by hazal.sener+yew@sqldbm.com **

-- ************************************** demo.andy.parent
CREATE TABLE demo.andy.parent
(
 id   int NOT NULL CONSTRAINT pk_1 PRIMARY KEY,
 name int NOT NULL
)
USING DELTA
 TBLPROPERTIES (delta.parquet.compression.codec = 'zstd', delta.minWriterVersion = 7, delta.feature.rowTracking = 'supported', delta.feature.appendOnly = 'supported', delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.feature.domainMetadata = 'supported', delta.checkpoint.writeStatsAsStruct = true, delta.enableRowTracking = true, delta.checkpoint.writeStatsAsJson = false, delta.columnMapping.mode = 'name', delta.feature.deletionVectors = 'supported', delta.rowTracking.materializedRowCommitVersionColumnName = '_row-commit-version-col-56413d65-7512-409f-ac9f-873510fa65d1', delta.feature.columnMapping = 'supported', delta.rowTracking.materializedRowIdColumnName = '_row-id-col-7ba53818-f6b4-46f1-95b7-565a989b47b9', delta.feature.invariants = 'supported');
