-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: test project by hazal.sener+yew@sqldbm.com **

-- ************************************** demo.andy.testtable
CREATE TABLE demo.andy.testtable
(
 dec int
)
USING DELTA
 TBLPROPERTIES (delta.parquet.compression.codec = 'zstd', delta.minWriterVersion = 7, delta.feature.rowTracking = 'supported', delta.feature.appendOnly = 'supported', delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.feature.domainMetadata = 'supported', delta.checkpoint.writeStatsAsStruct = true, delta.writePartitionColumnsToParquet = true, delta.enableRowTracking = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.rowTracking.materializedRowCommitVersionColumnName = '_row-commit-version-col-9933b6d6-de74-4b0c-abb8-f860eb7c1f20', delta.rowTracking.materializedRowIdColumnName = '_row-id-col-3bc16d3f-8f56-4cba-a920-f518182d8bc7', delta.feature.invariants = 'supported');
