-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: test project by hazal.sener+yew@sqldbm.com **

-- ************************************** demo.andy.test
CREATE TABLE demo.andy.test
(
 original_message          binary,
 kafka_message_key         string,
 kafka_topic               string,
 kafka_partition           int,
 kafka_offset              bigint,
 kafka_timestamp           timestamp,
 kafka_headers             array<struct<key:string,value:string>>,
 eventId                   string,
 eventTimestamp            string,
 transactionInitiated      string,
 transactionUpdated        string,
 eventType                 string,
 state                     string,
 rgs                       string,
 transactionRef            string,
 activityRef               string,
 userId                    bigint,
 gameId                    string,
 tournamentRef             string,
 tournamentCommonGroupCode string,
 amount                    string,
 token                     struct<code:string,value:string>,
 walletReference           string,
 bountyType                string,
 error                     string,
 inserted_ts               timestamp
)
USING DELTA
 TBLPROPERTIES (delta.parquet.compression.codec = 'zstd', delta.minWriterVersion = 7, delta.feature.rowTracking = 'supported', delta.feature.appendOnly = 'supported', delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.feature.domainMetadata = 'supported', delta.checkpoint.writeStatsAsStruct = true, delta.enableRowTracking = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.rowTracking.materializedRowCommitVersionColumnName = '_row-commit-version-col-c2a6900c-41b6-4097-820e-55e8c1111d82', delta.rowTracking.materializedRowIdColumnName = '_row-id-col-1fef2001-59d5-4b97-8ecd-8ceb122f8111', delta.feature.invariants = 'supported');
