-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: test project by hazal.sener+yew@sqldbm.com **

-- ************************************** demo.andy.child
CREATE TABLE demo.andy.child
(
 id       int NOT NULL CONSTRAINT pk_2 PRIMARY KEY,
 parentId int NOT NULL CONSTRAINT fk_1 REFERENCES demo.andy.parent (id),
 name     int NOT NULL
)
USING DELTA
 TBLPROPERTIES (delta.parquet.compression.codec = 'zstd', delta.minWriterVersion = 7, delta.feature.rowTracking = 'supported', delta.feature.appendOnly = 'supported', delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.feature.domainMetadata = 'supported', delta.checkpoint.writeStatsAsStruct = true, delta.enableRowTracking = true, delta.checkpoint.writeStatsAsJson = false, delta.columnMapping.mode = 'name', delta.feature.deletionVectors = 'supported', delta.rowTracking.materializedRowCommitVersionColumnName = '_row-commit-version-col-c5399f08-97c6-40ed-adaa-5aa893982941', delta.feature.columnMapping = 'supported', delta.rowTracking.materializedRowIdColumnName = '_row-id-col-2ab55f38-f097-4137-a027-298284f69e3f', delta.feature.invariants = 'supported');
