-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** audit_data_load_log
CREATE TABLE IF NOT EXISTS audit_data_load_log
(
 load_id               int NOT NULL CONSTRAINT pk_audit_data_load_log PRIMARY KEY,
 load_timestamp        timestamp NOT NULL,
 table_name            string NOT NULL,
 record_cnt            int NOT NULL,
 load_status           string NOT NULL,
 error_message         string,
 load_duration_seconds int
);
