-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** audit_data_quality
CREATE TABLE IF NOT EXISTS audit_data_quality
(
 quality_check_id int NOT NULL CONSTRAINT pk_audit_data_quality PRIMARY KEY,
 check_timestamp  timestamp NOT NULL,
 table_name       string NOT NULL,
 check_type       string NOT NULL,
 check_desc       string,
 records_checked  int,
 records_failed   int,
 check_status     string NOT NULL
);
