-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** bridge_supplier_product
CREATE TABLE IF NOT EXISTS bridge_supplier_product
(
 supplier_product_id    int NOT NULL CONSTRAINT pk_bridge_supplier_product PRIMARY KEY,
 supplier_id            int NOT NULL CONSTRAINT fk_supp_prod_supplier REFERENCES dim_supplier,
 product_id             int NOT NULL CONSTRAINT fk_supp_prod_product REFERENCES dim_product,
 supplier_sku           string,
 supplier_prc           decimal(12, 4) NOT NULL,
 minimum_order_quantity decimal(12, 4),
 last_order_dt          date
);
