-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** bridge_store_product
CREATE TABLE IF NOT EXISTS bridge_store_product
(
 store_product_id int NOT NULL CONSTRAINT pk_bridge_store_product PRIMARY KEY,
 store_id         int NOT NULL CONSTRAINT fk_store_prod_store REFERENCES dim_store,
 product_id       int NOT NULL CONSTRAINT fk_store_prod_product REFERENCES dim_product,
 display_location string,
 promotional_prc  decimal(12, 4),
 effective_from   date NOT NULL,
 effective_to     date
);
