-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** bridge_product_recipe
CREATE TABLE IF NOT EXISTS bridge_product_recipe
(
 recipe_id             int NOT NULL CONSTRAINT pk_bridge_product_recipe PRIMARY KEY,
 finished_product_id   int NOT NULL CONSTRAINT fk_recipe_finished REFERENCES dim_product (product_id),
 ingredient_product_id int NOT NULL,
 quantity_required     decimal(12, 4) NOT NULL,
 unit_of_measure       string NOT NULL
);
