-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** bridge_promotion_product
CREATE TABLE IF NOT EXISTS bridge_promotion_product
(
 promo_product_id int NOT NULL CONSTRAINT pk_bridge_promotion_product PRIMARY KEY,
 promotion_id     int NOT NULL CONSTRAINT fk_promo_prod_promotion REFERENCES dim_promotion,
 product_id       int NOT NULL CONSTRAINT fk_promo_prod_product REFERENCES dim_product,
 discnt_pct       decimal(5, 2),
 discnt_amt       decimal(12, 4)
);
