-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** bronze_sales_raw
CREATE TABLE IF NOT EXISTS bronze_sales_raw
(
 sales_raw_id        string NOT NULL COMMENT 'Unique identifier for raw sales record' CONSTRAINT pk_39 PRIMARY KEY,
 raw_data            string COMMENT 'Full JSON or CSV payload of sales record',
 ingestion_timestamp timestamp NOT NULL COMMENT 'Timestamp when data was ingested'
)
 COMMENT 'Raw sales data ingested directly from source system';
