-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** bronze_inventory_raw
CREATE TABLE IF NOT EXISTS bronze_inventory_raw
(
 inventory_raw_id    string NOT NULL COMMENT 'Unique identifier for raw inventory record',
 raw_data            string COMMENT 'Full JSON or CSV payload of inventory record',
 ingestion_timestamp timestamp NOT NULL COMMENT 'Timestamp when data was ingested',
 new_col             string NOT NULL
)
 COMMENT 'Raw inventory data ingested directly from source system';
