-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** CUSS
CREATE TABLE CUSS
(
 CUSS_id     number(38,0) NOT NULL,
 supplier_id number(38,0) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( CUSS_id ),
 CONSTRAINT FK_1 FOREIGN KEY ( supplier_id ) REFERENCES supplier ( supplier_id )
);
