-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** CUSS.Interactions
CREATE TABLE CUSS.Interactions
(
 InteractionID   integer NOT NULL AUTOINCREMENT COMMENT 'A unique identifier for each interaction record in the table. This primary key ensures that each entry is distinct and can be referenced individually. It''s typically generated automatically by the system',
 CUSSID          integer NOT NULL COMMENT 'Reference to the unique identifier of the customer involved in the interaction',
 InteractionType varchar(16777216) COMMENT 'Specifies the type of interaction that occurred between the customer and the company. This could include values such as "Email," "Phone Call," "Support Ticket," "Live Chat," or other forms of communication or engagement. This field helps categorize and analyze different ways the company interacts with its customers.',
 InteractionDate date COMMENT 'The date (and optionally the time) when the interaction took place. This timestamp provides context for when the interaction occurred and can be used for tracking engagement patterns, measuring response times, and analyzing customer communication over time.',

 CONSTRAINT PK_Interactions PRIMARY KEY ( InteractionID, CUSSID ),
 CONSTRAINT FK_CUSSInteractions FOREIGN KEY ( CUSSID ) REFERENCES CUSS.CUSS ( CUSSID ) COMMENT 'The Customer Interactions relationship links the Customers table to the Interactions table, representing the various engagements or communications that a customer has with the company. This is an optional, one-to-many relationship, meaning that while a customer may have multiple interactions (or none at all), each interaction is linked to one specific customer. This relationship enables the tracking and analysis of how customers engage with the company, providing insights into customer behavior, preferences, and the effectiveness of customer service and marketing efforts.

This relationship helps maintain a comprehensive view of each customer''s journey and touchpoints, supporting personalized communication strategies and customer management initiatives.'
)
COMMENT = 'Records of communications or engagements with customers';
