-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** CUSS.CUSS
CREATE TABLE CUSS.CUSS
(
 CUSSID integer NOT NULL AUTOINCREMENT COMMENT 'A unique identifier for each customer in the table. This primary key ensures that each customer is distinct within the database. It''s used to uniquely identify and link customer data across related tables (e.g., Interactions, Orders).',
 Name   varchar(16777216) COMMENT 'The full name of the customer, which may include first name, last name, and middle names or initials if applicable. This field is used to personalize communications and identify customers within business processes. The name can also help in differentiating between multiple customers in customer service scenarios.',
 Email  varchar(16777216) COMMENT 'The email address of the customer, used for communication, notifications, and marketing purposes. This field serves as a primary contact method and is crucial for customer engagement, support, and account management. The email is often used for unique identification purposes in addition to the CustomerID',

 CONSTRAINT PK_CUSSs PRIMARY KEY ( CUSSID )
)
COMMENT = 'Individuals or entities who purchase products or services.';
