-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "DIM_SHIPPING_METHOD"
CREATE OR REPLACE TABLE "DIM_SHIPPING_METHOD"
(
 "SHIPPING_METHOD_ID"   varchar(50) NOT NULL,
 "SHIPPING_METHOD_NAME" varchar(100) NOT NULL,
 "SHIPPING_TYPE"        varchar(50),
 "DESC"                 text,
 "ORDER_LINE_ID"        string NOT NULL,

 CONSTRAINT "pk_DIM_SHIPPING_METHOD" PRIMARY KEY ( "SHIPPING_METHOD_ID" )
);
