-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "DIM_DATE"
CREATE TABLE IF NOT EXISTS "DIM_DATE"
(
 "DATE"    date,
 "YEAR"    number(4),
 "QUARTER" number(1),
 "MONTH"   number(2),
 "DAY"     number(2)
);
