-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** dim_cuisine_type
CREATE TABLE IF NOT EXISTS dim_cuisine_type
(
 cuisine_type_id int NOT NULL CONSTRAINT pk_dim_cuisine_type PRIMARY KEY,
 cuisine_name    string NOT NULL,
 desc            string
);
