-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** dim_promotion
CREATE TABLE IF NOT EXISTS dim_promotion
(
 promotion_id int NOT NULL CONSTRAINT pk_dim_promotion PRIMARY KEY,
 promotion_cd string NOT NULL
);
