-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "DIM_PAYMENT_METHOD"
CREATE OR REPLACE TABLE "DIM_PAYMENT_METHOD"
(
 "PAYMENT_METHOD_ID"   varchar(50) NOT NULL,
 "PAYMENT_METHOD_NAME" varchar(100) NOT NULL,
 "PAYMENT_CATEGORY"    varchar(50),
 "DESC"                text,

 CONSTRAINT "pk_DIM_PAYMENT_METHOD" PRIMARY KEY ( "PAYMENT_METHOD_ID" )
);
