-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** dim_electronics
CREATE TABLE IF NOT EXISTS dim_electronics
(
 category_id int NOT NULL CONSTRAINT pk_1 PRIMARY KEY, CONSTRAINT fk_1 FOREIGN KEY (category_id) REFERENCES dim_product_category
);
