-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** dim_customer
CREATE TABLE IF NOT EXISTS dim_customer
(
 customer_id int NOT NULL CONSTRAINT pk_dim_customer PRIMARY KEY,
 customer_cd string NOT NULL
);
