-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** dim_employee
CREATE TABLE IF NOT EXISTS dim_employee
(
 employee_id int NOT NULL CONSTRAINT pk_dim_employee PRIMARY KEY,
 employee_cd string NOT NULL
);
