-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "DIM_HUB_"
CREATE OR REPLACE TABLE "DIM_HUB_"
(
 "MD5_HUB_"      binary NOT NULL,
 "FROM_DTS"      timestamp_ntz(9) NOT NULL,
 "TO_DTS"        timestamp_ntz(9) NOT NULL,
 "DW_CREATED_TS" datetime NOT NULL,
 "CREATED_BY"    string NOT NULL,
 "UPDTD_TS"      timestamp NOT NULL,
 "UPDTD_BY"      varchar(50) NOT NULL,
 "IS_UPDTD"      boolean NOT NULL,
 "TEST"          timestamp_ntz NOT NULL COMMENT 'test desc',
 "LOAD_DTS"      timestamp_ntz(9) NOT NULL,
 "REC_SRC"       varchar(16777216) NOT NULL,
 "LOAD_DTS_1"    timestamp_ntz(9) NOT NULL,

 CONSTRAINT "pk_DIM_HUB_" PRIMARY KEY ( "MD5_HUB_", "FROM_DTS" )
);
