-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "DIM_DT"
CREATE OR REPLACE TABLE "DIM_DT"
(
 "DT_KEY"       integer NOT NULL,
 "CALENDAR_DT"  date NOT NULL,
 "YEAR"         integer,
 "QUARTER"      integer,
 "MONTH"        integer,
 "DAY_OF_MONTH" integer,
 "DAY_OF_WEEK"  integer,
 "WEEK_OF_YEAR" integer,
 "IS_WEEKEND"   boolean,

 CONSTRAINT "pk_DIM_DT" PRIMARY KEY ( "DT_KEY" )
);
