-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "DIM_CUSTOMER"
CREATE OR REPLACE TABLE "DIM_CUSTOMER"
(
 "CUSTOMER_ID"      varchar(50) NOT NULL,
 "CUSTOMER_NAME"    varchar(255) NOT NULL,
 "CUSTOMER_TYPE"    varchar(100),
 "CUSTOMER_SEGMENT" varchar(100),
 "CUSTOMER_COUNTRY" varchar(100),
 "IS_ACTIVE"        boolean DEFAULT TRUE,
 "CREATED_DT"       timestamp_ntz DEFAULT CURRENT_TIMESTAMP(),
 "UPDTD_DT"         timestamp_ntz DEFAULT CURRENT_TIMESTAMP(),

 CONSTRAINT "pk_DIM_CUSTOMER" PRIMARY KEY ( "CUSTOMER_ID" )
);
