-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "DIM_SUPPLIER"
CREATE OR REPLACE TABLE "DIM_SUPPLIER"
(
 "SUPPLIER_ID"      varchar(50) NOT NULL,
 "SUPPLIER_NAME"    varchar(255) NOT NULL,
 "SUPPLIER_COUNTRY" varchar(100),
 "SUPPLIER_RATING"  integer,
 "SUPPLIER_STATUS"  varchar(50),
 "CREATED_DT"       timestamp_ntz DEFAULT CURRENT_TIMESTAMP(),
 "UPDTD_DT"         timestamp_ntz DEFAULT CURRENT_TIMESTAMP(),

 CONSTRAINT "pk_DIM_SUPPLIER" PRIMARY KEY ( "SUPPLIER_ID" )
);
