-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** dim_payment_method
CREATE TABLE IF NOT EXISTS dim_payment_method
(
 payment_method_id   int NOT NULL CONSTRAINT pk_dim_payment_method PRIMARY KEY,
 payment_method_name string NOT NULL,
 payment_type        string NOT NULL,
 desc                string
);
