-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** dim_product_category
CREATE TABLE IF NOT EXISTS dim_product_category
(
 category_id        int NOT NULL COMMENT 'Unique surrogate key identifier for the product category' CONSTRAINT pk_dim_product_category PRIMARY KEY,
 category_name      string NOT NULL COMMENT 'Business name of the product category',
 category_desc      string COMMENT 'Detailed description of the product category',
 parent_category_id int COMMENT 'Reference to the parent category identifier for hierarchical classification',
 department         string NOT NULL COMMENT 'Department or business unit that manages this product category'
)
 COMMENT 'Dimension table containing product category attributes and hierarchy for analytical reporting';
