-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** dim_product_subcategory
CREATE TABLE IF NOT EXISTS dim_product_subcategory
(
 subcategory_id   int NOT NULL,
 category_id_1    int NOT NULL CONSTRAINT fk_2 REFERENCES dim_product_category (category_id),
 subcategory_name string NOT NULL,
 category_id      int NOT NULL,
 CONSTRAINT pk_dim_product_subcategory PRIMARY KEY (subcategory_id, category_id_1)
);
