-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** dim_brand
CREATE TABLE IF NOT EXISTS dim_brand
(
 brand_id           int NOT NULL CONSTRAINT pk_dim_brand PRIMARY KEY,
 brand_name         string NOT NULL,
 brand_origin_cntry string,
 brand_type         string NOT NULL,
 is_premium         boolean NOT NULL,
 market_segment     string
);
