-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "DIM_GEOGRAPHY"
CREATE TABLE IF NOT EXISTS "DIM_GEOGRAPHY"
(
 "GEOGRAPHY_HKEY" number,
 "COUNTRY_NAME"   varchar(100),
 "STATE_CD"       varchar(10),
 "CITY_NAME"      varchar(150)
);
