-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** dim_store
CREATE TABLE IF NOT EXISTS dim_store
(
 store_id int NOT NULL CONSTRAINT pk_dim_store PRIMARY KEY,
 store_cd string NOT NULL
);
