-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "DIM_PRODUCT"
CREATE OR REPLACE TABLE "DIM_PRODUCT"
(
 "PRODUCT_ID"          varchar(50) NOT NULL COMMENT 'Unique identifier for each product.',
 "PRODUCT_NAME"        varchar(255) NOT NULL COMMENT 'The name or title of the product.',
 "PRODUCT_CATEGORY"    varchar(100) COMMENT 'The primary category classification for the product.',
 "PRODUCT_SUBCATEGORY" varchar(100) COMMENT 'The secondary category classification providing more detailed product segmentation.',
 "PRODUCT_PRICE"       decimal(15,4) COMMENT 'The selling price of the product.',
 "IS_ACTIVE"           boolean DEFAULT TRUE COMMENT 'Flag indicating whether the product is currently active in the catalog.',
 "CREATED_DT"          timestamp_ntz DEFAULT CURRENT_TIMESTAMP() COMMENT 'Timestamp when the product record was created.',
 "UPDTD_DT"            timestamp_ntz DEFAULT CURRENT_TIMESTAMP() COMMENT 'Timestamp when the product record was last updated.',

 CONSTRAINT "pk_DIM_PRODUCT" PRIMARY KEY ( "PRODUCT_ID" )
)
COMMENT = 'Dimension table containing product information including identifiers, names, categories, pricing, and status tracking.';
