-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** dim_supplier
CREATE TABLE IF NOT EXISTS dim_supplier
(
 supplier_id int NOT NULL CONSTRAINT pk_dim_supplier PRIMARY KEY,
 supplier_cd string NOT NULL
);
