-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** dim_dt
CREATE TABLE IF NOT EXISTS dim_dt
(
 dt_id          int NOT NULL CONSTRAINT pk_dim_dt PRIMARY KEY,
 calendar_dt    date NOT NULL,
 `year`         int NOT NULL,
 quarter        int NOT NULL,
 month          int NOT NULL,
 day            int NOT NULL,
 day_of_week    int NOT NULL,
 day_name       string NOT NULL,
 week_of_year   int NOT NULL,
 is_weekend     boolean NOT NULL,
 is_holiday     boolean NOT NULL,
 holiday_name   string,
 fiscal_year    int NOT NULL,
 fiscal_quarter int NOT NULL,
 fiscal_month   int NOT NULL
);
