-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** dim_product
CREATE TABLE IF NOT EXISTS dim_product
(
 product_id int NOT NULL CONSTRAINT pk_dim_product PRIMARY KEY,
 product_cd string NOT NULL
);
