-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** edw_fb_staging_1.stg_inventory_raw
CREATE TABLE IF NOT EXISTS edw_fb_staging_1.stg_inventory_raw
(
 store_id          int NOT NULL COMMENT 'Identifier of the store location',
 product_id        int NOT NULL COMMENT 'Identifier of the product in inventory',
 dt                date COMMENT 'Date of the inventory record',
 quantity_on_hand  decimal(12, 4) COMMENT 'Current quantity of the product in stock',
 quantity_reserved decimal(12, 4) COMMENT 'Quantity of product reserved or allocated',
 reorder_level     decimal(12, 4) COMMENT 'Stock level at which a reorder should be triggered',
 reorder_quantity  decimal(12, 4) COMMENT 'Recommended quantity to order when restocking',
 load_timestamp    timestamp COMMENT 'Timestamp when the inventory data was loaded into the system',
 sales_raw_id      string NOT NULL COMMENT 'Unique identifier for raw sales record',
 inventory_raw_id  string NOT NULL COMMENT 'Unique identifier for raw inventory record' CONSTRAINT fk_41 REFERENCES bronze_inventory_raw,
 CONSTRAINT pk_38 PRIMARY KEY (store_id, product_id)
)
 COMMENT 'Staging table for raw inventory data, tracking product stock levels and inventory movements.';
