-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** edw_fb_staging_1.stg_sales_raw
CREATE TABLE IF NOT EXISTS edw_fb_staging_1.stg_sales_raw
(
 sales_id          int NOT NULL COMMENT 'Unique identifier for each sales transaction',
 transaction_dt    date NOT NULL COMMENT 'Date of the sales transaction',
 product_id        int COMMENT 'Identifier of the product sold',
 customer_id       int COMMENT 'Identifier of the customer making the purchase',
 store_id          int COMMENT 'Identifier of the store where the transaction occurred',
 employee_id       int COMMENT 'Identifier of the employee who processed the transaction',
 payment_method_id int COMMENT 'Identifier of the payment method used',
 promotion_id      int COMMENT 'Identifier of any promotional offer applied to the transaction',
 quantity_sold     decimal(12, 4) COMMENT 'Number of units sold in the transaction',
 unit_prc          decimal(12, 4) COMMENT 'Price per unit of the product',
 discnt_amt        decimal(12, 4) COMMENT 'Total discount applied to the transaction',
 tax_amt           decimal(12, 4) COMMENT 'Total tax charged for the transaction',
 total_amt         decimal(15, 4) COMMENT 'Total monetary value of the transaction',
 transaction_time  string COMMENT 'Time of the sales transaction',
 load_timestamp    timestamp COMMENT 'Product category identifier',
 stock_quantity    string NOT NULL COMMENT 'Current stock quantity' CONSTRAINT fk_41_1 REFERENCES bronze_sales_raw (sales_raw_id),
 CONSTRAINT pk_40 PRIMARY KEY (sales_id, transaction_dt)
)
 COMMENT 'Staging table for raw sales transaction data, capturing detailed sales events with comprehensive transaction details.';
