-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** fact_purchase_order
CREATE TABLE IF NOT EXISTS fact_purchase_order
(
 purchase_order_id    decimal(12, 4) NOT NULL CONSTRAINT pk_fact_purchase_order PRIMARY KEY,
 order_dt_id          decimal(12, 4) NOT NULL,
 product_id           decimal(12, 4) NOT NULL CONSTRAINT fk_po_product REFERENCES dim_product,
 supplier_id          decimal(12, 4) NOT NULL,
 store_id             decimal(12, 4) NOT NULL,
 quantity_ordered     decimal(12, 4) NOT NULL,
 unit_cost            decimal(12, 4) NOT NULL,
 order_total          decimal(15, 4) NOT NULL,
 expected_delivery_dt date,
 actual_delivery_dt   date,
 order_status         de NOT NULL,
 payment_status       string NOT NULL
);
