-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** fact_customer_feedback
CREATE TABLE IF NOT EXISTS fact_customer_feedback
(
 feedback_id       int NOT NULL CONSTRAINT pk_fact_customer_feedback PRIMARY KEY,
 feedback_dt_id    int NOT NULL CONSTRAINT fk_feedback_dt REFERENCES dim_dt (dt_id),
 customer_id       int NOT NULL CONSTRAINT fk_feedback_customer REFERENCES dim_customer,
 product_id        int NOT NULL CONSTRAINT fk_feedback_product REFERENCES dim_product,
 store_id          int NOT NULL,
 rating            int NOT NULL,
 comments          string,
 category          string NOT NULL,
 resolution_status string
);
