-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** fact_employee_performance
CREATE TABLE IF NOT EXISTS fact_employee_performance
(
 performance_id              int NOT NULL CONSTRAINT pk_fact_employee_performance PRIMARY KEY,
 dt_id                       int NOT NULL CONSTRAINT fk_perf_dt REFERENCES dim_dt,
 employee_id                 int NOT NULL,
 store_id                    int NOT NULL,
 sales_achieved              decimal(15, 4),
 sales_target                decimal(15, 4),
 customer_satisfaction_score decimal(3, 2),
 attendance_hours            decimal(10, 2),
 productivity_score          decimal(3, 2),
 training_hours              decimal(5, 2),
 performance_rating          string
);
