-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** fact_inventory
CREATE TABLE IF NOT EXISTS fact_inventory
(
 inventory_id       int NOT NULL CONSTRAINT pk_fact_inventory PRIMARY KEY,
 dt_id              int NOT NULL CONSTRAINT fk_inv_dt REFERENCES dim_dt,
 product_id         int NOT NULL,
 store_id           int NOT NULL,
 quantity_on_hand   decimal(12, 4) NOT NULL,
 quantity_available decimal(12, 4) NOT NULL,
 reorder_level      decimal(12, 4),
 reorder_quantity   decimal(12, 4),
 inventory_value    decimal(15, 4) NOT NULL,
 last_received_dt   date,
 last_sold_dt       date,
 shelf_location     string
);
