-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** fact_sales
CREATE TABLE IF NOT EXISTS fact_sales
(
 sales_id          int NOT NULL CONSTRAINT pk_fact_sales PRIMARY KEY,
 transaction_dt_id int NOT NULL,
 product_id        int NOT NULL,
 customer_id       int NOT NULL,
 store_id          int NOT NULL,
 employee_id       int,
 payment_method_id int NOT NULL,
 promotion_id      int,
 quantity_sold     decimal(12, 4) NOT NULL,
 unit_prc          decimal(12, 4) NOT NULL,
 tax_amt           decimal(12, 4) NOT NULL,
 total_amt         decimal(15, 4) NOT NULL,
 cost_amt          decimal(15, 4) NOT NULL,
 profit_amt        decimal(15, 4) NOT NULL
);
