-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** fact_production
CREATE TABLE IF NOT EXISTS fact_production
(
 production_id           int NOT NULL CONSTRAINT pk_fact_production PRIMARY KEY,
 production_dt_id        int NOT NULL CONSTRAINT fk_prod_dt REFERENCES dim_dt (dt_id),
 product_id              int NOT NULL,
 store_id                int NOT NULL CONSTRAINT fk_prod_store REFERENCES dim_store,
 employee_id             int CONSTRAINT fk_prod_employee REFERENCES dim_employee,
 quantity_produced       decimal(12, 4) NOT NULL,
 planned_quantity        decimal(12, 4) NOT NULL,
 raw_material_cost       decimal(15, 4) NOT NULL,
 labor_cost              decimal(15, 4) NOT NULL,
 production_time_minutes int,
 quality_score           decimal(3, 2),
 production_shift        string NOT NULL
);
