-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "FACT_SALES"
CREATE TABLE IF NOT EXISTS "FACT_SALES"
(
 "SALES_HKEY"      number,
 "GEOGRAPHY_HKEY"  number,
 "SALE_DATE"       date,
 "SOLD_QTY"        number,
 "TOTAL_SALES_AMT" number(18,2)
);
