-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "HUB_"
CREATE OR REPLACE TABLE "HUB_"
(
 "DW_CREATED_TS" datetime NOT NULL,
 "CREATED_BY"    string NOT NULL,
 "UPDTD_TS"      timestamp NOT NULL,
 "UPDTD_BY"      varchar(50) NOT NULL,
 "IS_UPDTD"      boolean NOT NULL,
 "TEST"          timestamp_ntz NOT NULL COMMENT 'test desc',
 "MD5_HUB_"      binary NOT NULL,
 "LOAD_DTS"      timestamp_ntz(9) NOT NULL,
 "REC_SRC"       varchar(16777216) NOT NULL,

 CONSTRAINT "pk_HUB_" PRIMARY KEY ( "MD5_HUB_" )
);
