-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** "Human Resources".Employee
CREATE TABLE "Human Resources".Employee
(
 EmployeeID                  integer NOT NULL AUTOINCREMENT COMMENT 'Description: A unique identifier for each employee in the table. This primary key ensures that each employee record is distinct and can be referenced individually.',
 FirstName                   varchar(16777216) COMMENT 'The first name of the employee. This field is used for identifying employees and personalizing communications. It helps in distinguishing employees, especially when combined with the last name.',
 LastName                    varchar(16777216) COMMENT 'The last name (surname) of the employee. This field, along with the first name, provides the full name of the employee, used for identification, documentation, and communication purposes within the organization.',
 Email                       varchar(16777216) COMMENT 'The email address of the employee. This field is used for official communication and serves as a primary contact method. It is also often used for system logins, notifications, and correspondence.',
 Role                        varchar(16777216) COMMENT 'The job role or position of the employee within the organization. This field describes the employee’s responsibilities and functions, such as "Sales Representative," "Manager," "Developer," or "Support Staff." It is crucial for assigning tasks, managing access permissions, and understanding the employee''s role in the company''s operations.',
 "Tax Identification Number" integer NOT NULL COMMENT 'TIN:  for the contractor, used for tax reporting and compliance purposes. This field is essential for distinguishing contractors from regular employees and for managing legal and financial obligations related to contract work.',

 CONSTRAINT PK_Employees PRIMARY KEY ( EmployeeID )
)
COMMENT = 'The Employees table contains information about the employees within the organization. It stores personal and professional details such as names, contact information, and job roles. This table is essential for managing employee records, facilitating communication, and supporting various HR and organizational processes.';
