-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** "Human Resources".EmployeeAssignments
CREATE TABLE "Human Resources".EmployeeAssignments
(
 AssignmentID integer NOT NULL AUTOINCREMENT COMMENT 'A unique identifier for each assignment record in the table. This primary key ensures that each assignment entry is distinct and can be referenced individually.',
 EmployeeID   integer COMMENT 'A reference to the unique identifier of the employee assigned to the specific task or project. This foreign key links to the Employees table, connecting each assignment to a specific employee and enabling the tracking of who is responsible for which tasks or projects.',
 CUSSID       integer NOT NULL COMMENT 'A unique identifier for each customer in the table. This primary key ensures that each customer is distinct within the database. It''s used to uniquely identify and link customer data across related tables (e.g., Interactions, Orders).',

 CONSTRAINT PK_EmployeeAssignments PRIMARY KEY ( AssignmentID ),
 CONSTRAINT FK_EmployeeAssignments_1 FOREIGN KEY ( EmployeeID ) REFERENCES "Human Resources".Employee ( EmployeeID )
)
COMMENT = 'The EmployeeAssignments table tracks the assignments or projects that employees are involved in within the organization. This table links employees to specific assignments, projects, tasks, or roles, enabling the organization to manage work distribution, track progress, and analyze employee involvement. It plays a crucial role in project management and resource allocation.';
