-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "INFOMART"."DIM_CAMPAIGN"
CREATE TABLE IF NOT EXISTS "INFOMART"."DIM_CAMPAIGN"
(
 "CAMPAIGN_HKEY"         binary(8388608) NOT NULL,
 "CAMPAIGN_ID"           number(38,0) NOT NULL,
 "CAMPAIGN_NAME"         varchar(255),
 "CAMPAIGN_START_DATE"   date,
 "CAMPAIGN_END_DATE"     date,
 "CAMPAIGN_STATUS_VALUE" varchar(25),

 CONSTRAINT "PK_DIM_CAMPAIGN" PRIMARY KEY ( "CAMPAIGN_HKEY" )
);
