-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "INFOMART"."DIM_CHANNEL"
CREATE TABLE IF NOT EXISTS "INFOMART"."DIM_CHANNEL"
(
 "CHANNEL_HKEY" binary(8388608) NOT NULL,
 "CHANNEL_NAME" varchar(255),
 "CHANNEL_TYPE" varchar(100),

 CONSTRAINT "PK_DIM_CHANNEL" PRIMARY KEY ( "CHANNEL_HKEY" )
);
