-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "INFOMART"."DIM_FORECAST_TYPE"
CREATE TABLE IF NOT EXISTS "INFOMART"."DIM_FORECAST_TYPE"
(
 "FORECAST_TYPE_HKEY" binary(8388608) NOT NULL,
 "FORECAST_TYPE_NAME" varchar(255),
 "DESCRIPTION"        varchar(255),

 CONSTRAINT "PK_DIM_FORECAST_TYPE" PRIMARY KEY ( "FORECAST_TYPE_HKEY" )
);
