-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "INFOMART"."DIM_EMPLOYEE"
CREATE TABLE IF NOT EXISTS "INFOMART"."DIM_EMPLOYEE"
(
 "EMPLOYEE_HK"      binary(8388608) NOT NULL,
 "EMPLOYEE_ID"      number(38,0) NOT NULL,
 "FIRST_NAME"       varchar(255),
 "LAST_NAME"        varchar(255),
 "ROLE_DESCRIPTION" varchar(100),
 "BIRTH_DATE"       date NOT NULL,

 CONSTRAINT "PK_DIM_EMPLOYEE" PRIMARY KEY ( "EMPLOYEE_HK" )
);
