-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "INFOMART"."TABLE_12"
CREATE TABLE IF NOT EXISTS "INFOMART"."TABLE_12"
(
 "CUSTOMER_HKEY" binary(8388608) NOT NULL,

 CONSTRAINT "FK_1" FOREIGN KEY ( "CUSTOMER_HKEY" ) REFERENCES "INFOMART"."DIM_CUSTOMER" ( "CUSTOMER_HKEY" )
);
