-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "INFOMART"."DIM_PRODUCT"
CREATE TABLE IF NOT EXISTS "INFOMART"."DIM_PRODUCT"
(
 "PRODUCT_HKEY"     binary(8388608) NOT NULL,
 "UPC_CD"           varchar(20) NOT NULL,
 "PRODUCT_NAME"     varchar(255),
 "CATEGORY_NAME"    varchar(255),
 "LIST_PRICE_AMT"   number(10,2),
 "PRODUCT_COST_AMT" number(10,2),
 "PRODUCT_GROUP"    varchar(50) NOT NULL,
 "PRODUCT_DESC"     varchar(16777216) NOT NULL,
 "PRODUCT_SIZE"     varchar(50) NOT NULL
);
