-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "INFOMART"."DIM_GEOGRAPHY"
CREATE TABLE IF NOT EXISTS "INFOMART"."DIM_GEOGRAPHY"
(
 "GEOGRAPHY_HKEY" binary(8388608) NOT NULL,
 "COUNTRY_NAME"   varchar(100),
 "STATE_CD"       varchar(100),
 "CITY_NAME"      varchar(100),
 "REGION_NAME"    varchar(100),

 CONSTRAINT "PK_DIM_GEOGRAPHY" PRIMARY KEY ( "GEOGRAPHY_HKEY" )
);
