-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "INFOMART"."TABLE_24"
CREATE TABLE IF NOT EXISTS "INFOMART"."TABLE_24"
(
 "FORECAST_TYPE_HKEY" binary(8388608) NOT NULL,

 CONSTRAINT "PK_1" PRIMARY KEY ( "FORECAST_TYPE_HKEY" ),
 CONSTRAINT "FK_1" FOREIGN KEY ( "FORECAST_TYPE_HKEY" ) REFERENCES "INFOMART"."DIM_FORECAST_TYPE" ( "FORECAST_TYPE_HKEY" )
);
