-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "INFOMART"."DIM_DATE"
CREATE TABLE IF NOT EXISTS "INFOMART"."DIM_DATE"
(
 "DATE"               date NOT NULL COMMENT 'The actual calendar date, serving as the primary reference for all date-related analysis.',
 "YEAR"               number(38,0) NOT NULL,
 "QUARTER"            number(38,0) NOT NULL,
 "MONTH"              number(38,0) NOT NULL,
 "DAY_OF_MONTH"       number(38,0) NOT NULL,
 "DAY_IN_YEAR_NBR"    number(38,0) NOT NULL,
 "WEEK_OF_YEAR"       number(38,0) NOT NULL,
 "FISCAL_YEAR"        number(38,0) NOT NULL,
 "FISCAL_QUARTER"     number(38,0) NOT NULL,
 "FISCAL_MONTH"       number(38,0) NOT NULL,
 "IS_HOLIDAY"         boolean NOT NULL,
 "HOLIDAY_NAME"       varchar(255) NOT NULL,
 "IS_SPECIAL_EVENT"   boolean NOT NULL,
 "SPECIAL_EVENT_NAME" varchar(255) NOT NULL,
 "SEASON_NAME"        varchar(255) NOT NULL,

 CONSTRAINT "PK_DIM_DATE" PRIMARY KEY ( "DATE" )
);
