-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Environments EDW by hazal.sener+yew@sqldbm.com *

-- ************************************** "INFOMART"."DIM_CUSTOMER"
CREATE TABLE IF NOT EXISTS "INFOMART"."DIM_CUSTOMER"
(
 "CUSTOMER_HKEY"          binary(8388608) NOT NULL,
 "CUSTOMER_NBR"           varchar(50) NOT NULL,
 "CUSTOMER_FIRST_NAME"    varchar(255) WITH TAG ("INFOMART"."PII" = 'NAME'),
 "CUSTOMER_EMAIL_ADDRESS" varchar(320) WITH TAG ("INFOMART"."PII" = 'ADDRESS'),
 "CUSTOMER_SEGMENT_CD"    varchar(10),
 "CUSTOMER_SHOW_SIZE"     number(38,0) NOT NULL,

 CONSTRAINT "PK_DIM_CUSTOMER" PRIMARY KEY ( "CUSTOMER_HKEY" )
) WITH TAG ("INFOMART"."DOMAIN" = 'SALES');
