-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** Marketing.CUSSSegments
CREATE TABLE IF NOT EXISTS Marketing.CUSSSegments
(
 SegmentID integer NOT NULL AUTOINCREMENT COMMENT 'A unique identifier for each customer segment in the table. This primary key ensures that each segment record is distinct and can be referenced individually, allowing for precise targeting and tracking in marketing activities.',
 Name      varchar(16777216) COMMENT 'A detailed description of the customer segment, explaining the key traits, behaviors, demographics, or purchasing patterns that define the group. This field provides insights into why this segment is important for marketing efforts, such as their potential lifetime value, preferred channels, or responsiveness to specific types of offers or messaging. This information is crucial for crafting targeted campaigns, personalizing customer experiences, and driving effective marketing strategies',

 CONSTRAINT PK_CUSSSegments PRIMARY KEY ( SegmentID )
)
COMMENT = 'The CustomerSegments table stores information about the different customer segments defined for marketing purposes. Customer segments are distinct groups of customers categorized based on shared characteristics, behaviors, or demographics that are relevant to marketing strategies. This table helps in identifying target audiences, personalizing marketing campaigns, and optimizing customer engagement and acquisition efforts.';
