-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** Marketing.Campaigns
CREATE TABLE IF NOT EXISTS Marketing.Campaigns
(
 CampaignID  integer NOT NULL AUTOINCREMENT COMMENT 'A unique identifier for each campaign in the table. This primary key ensures that each campaign record is distinct and can be referenced individually.',
 Name        varchar(16777216) COMMENT 'The name of the campaign. This field provides a concise, descriptive label for the campaign, making it easy to identify and refer to in reports, dashboards, and other analyses.',
 Description varchar(16777216) COMMENT 'A detailed description of the campaign, including its goals, target audience, strategies, and key activities. This field helps provide context and understanding of the campaign’s purpose and scope.',
 StartDate   date COMMENT 'The date when the campaign is scheduled to start or was launched. This field helps in planning, tracking the campaign''s timeline, and measuring its performance from the initiation point.',
 EndDate     date COMMENT 'The date when the campaign is scheduled to end or was concluded. This field is used to define the campaign’s duration and helps in analyzing the campaign’s effectiveness over its operational period.',
 Status      varchar(16777216) COMMENT 'The current status of the campaign, such as "Planned," "Active," "Completed," or "Cancelled." This field helps track the progress of the campaign and supports decision-making regarding ongoing and future marketing activities.',

 CONSTRAINT PK_Campaigns PRIMARY KEY ( CampaignID )
)
COMMENT = 'The Campaigns table stores information about marketing or sales campaigns conducted by the organization. This table captures details about each campaign, including its objectives, duration, and current status. It is essential for tracking and managing marketing activities, analyzing campaign effectiveness, and linking campaigns to sales orders and customer interactions.';
