-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** Marketing.CampaignTargets
CREATE TABLE Marketing.CampaignTargets
(
 CampaignTargetID integer NOT NULL AUTOINCREMENT COMMENT 'A unique identifier for each campaign target record in the table. This primary key ensures that each entry is distinct and can be referenced individually.',
 CampaignID       integer COMMENT 'A reference to the unique identifier of the campaign associated with the target segment. This foreign key links to the Campaigns table, connecting each targeting record with a specific campaign and enabling the analysis of which segments are targeted by each marketing effort.',
 SegmentID        integer COMMENT 'A reference to the unique identifier of the customer segment that the campaign is targeting. This foreign key links to the CustomerSegments table, specifying the audience group for the campaign. It helps in managing and understanding the alignment of campaigns with specific customer segments.',

 CONSTRAINT PK_CampaignTargets PRIMARY KEY ( CampaignTargetID ),
 CONSTRAINT FK_CampaignTargets_1 FOREIGN KEY ( CampaignID ) REFERENCES Marketing.Campaigns ( CampaignID ),
 CONSTRAINT FK_CampaignTargets_2 FOREIGN KEY ( SegmentID ) REFERENCES Marketing.CUSSSegments ( SegmentID )
)
COMMENT = 'The CampaignTargets table links specific campaigns to targeted customer segments, defining the audiences that each campaign aims to reach. This table is crucial for managing and analyzing the targeting strategy of campaigns, allowing the organization to align marketing efforts with specific groups of customers based on their characteristics or behaviors.';
