-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** Product.Products
CREATE TABLE Product.Products
(
 ProductID             integer NOT NULL AUTOINCREMENT COMMENT 'A unique identifier for each product in the table. This primary key ensures that each product record is distinct and can be referenced individually',
 Name                  varchar(16777216) COMMENT 'The name of the product. This field is used to identify and describe the product in a recognizable and user-friendly way. It helps customers and staff easily identify products and can be used in search and reporting functions.',
 Price                 decimal(10,2) COMMENT 'The selling price of the product. This field represents the cost at which the product is offered for sale, excluding taxes and discounts. It is used for calculating sales revenue, managing pricing strategies, and processing transactions.',
 "Product Type"        varchar(16777216) NOT NULL,
 Genere                varchar(16777216) NOT NULL,
 "Author Name"         varchar(16777216) NOT NULL,
 "ISBN Number"         varchar(16777216) NOT NULL,
 "Type Code"           varchar(16777216) NOT NULL,
 "Designer Name"       varchar(16777216) NOT NULL,
 "Size Code"           varchar(16777216) NOT NULL,
 "Electronic Category" varchar(16777216) NOT NULL,

 CONSTRAINT PK_Products PRIMARY KEY ( ProductID )
)
COMMENT = 'General term for any item available for sale.';
