-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** Product.Suppliers
CREATE TABLE Product.Suppliers
(
 SupplierID integer NOT NULL AUTOINCREMENT COMMENT 'A unique identifier for each supplier in the table. This primary key ensures that each supplier record is distinct and can be referenced individually',
 Name       varchar(16777216) COMMENT 'The name of the supplier. This field is used to identify and describe the supplier in a recognizable and user-friendly way. It helps in managing supplier relationships, referencing suppliers in purchase orders, and ensuring clear communication regarding procurement activities.',

 CONSTRAINT PK_Suppliers PRIMARY KEY ( SupplierID )
)
COMMENT = 'Entities that provide products or components to the company, linking products to their respective suppliers.';
