-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** Product.ProductSuppliers
CREATE TABLE IF NOT EXISTS Product.ProductSuppliers
(
 ProductSupplierID integer NOT NULL AUTOINCREMENT COMMENT 'A unique identifier for each record in the table. This primary key ensures that each product-supplier relationship is distinct and can be referenced individually',
 ProductID         integer COMMENT 'A reference to the unique identifier of the product associated with the supplier. This foreign key links to the Product table, specifying which product is being supplied. It helps in tracking which products are available from which suppliers.',
 SupplierID        integer COMMENT 'A reference to the unique identifier of the supplier providing the product. This foreign key links to the Suppliers table, indicating the source of the product. It helps in managing supplier relationships and sourcing details for the products.',

 CONSTRAINT PK_ProductSuppliers PRIMARY KEY ( ProductSupplierID ),
 CONSTRAINT FK_ProductSuppliers_1 FOREIGN KEY ( ProductID ) REFERENCES Product.Products ( ProductID ),
 CONSTRAINT FK_ProductSuppliers_2 FOREIGN KEY ( SupplierID ) REFERENCES Product.Suppliers ( SupplierID )
)
COMMENT = 'Vendors who provide products or materials';
