-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** Product.Inventory
CREATE TABLE IF NOT EXISTS Product.Inventory
(
 InventoryID integer NOT NULL AUTOINCREMENT COMMENT 'A unique identifier for each inventory record in the table. This primary key ensures that each inventory entry is distinct and can be referenced individually',
 ProductID   integer COMMENT 'A reference to the unique identifier of the product associated with the inventory record. This foreign key links to the Product table, allowing the company to associate inventory levels with specific products and track stock availability for each item.',
 Quantity    integer COMMENT 'The number of units of the product currently in inventory. This field represents the stock level for each product, helping the company manage inventory levels, reorder supplies, and fulfill customer orders efficiently.',

 CONSTRAINT PK_Inventory PRIMARY KEY ( InventoryID ),
 CONSTRAINT FK_ProductInventory FOREIGN KEY ( ProductID ) REFERENCES Product.Products ( ProductID )
)
COMMENT = 'Stock of products available for sale.';
