-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** Product.PurchaseOrders
CREATE TABLE Product.PurchaseOrders
(
 PurchaseOrderID integer NOT NULL AUTOINCREMENT COMMENT 'A unique identifier for each purchase order in the table. This primary key ensures that each purchase order record is distinct and can be referenced individually',
 SupplierID      integer COMMENT 'A reference to the unique identifier of the supplier from whom the purchase order is made. This foreign key links to the Suppliers table, associating the purchase order with a specific supplier and facilitating tracking and management of procurement activities.',
 OrderDate       date COMMENT 'The date (and optionally the time) when the purchase order was created. This field helps in tracking the timing of procurement activities, managing supplier deliveries, and monitoring order processing timelines.',
 Status          varchar(16777216) COMMENT 'The current status of the purchase order, such as "Pending," "Approved," "Shipped," "Received," or "Cancelled." This field provides insight into the order''s progress through the procurement process and is crucial for managing order fulfillment and supplier interactions.',

 CONSTRAINT PK_PurchaseOrders PRIMARY KEY ( PurchaseOrderID ),
 CONSTRAINT FK_SuppliersPurchaseOrders FOREIGN KEY ( SupplierID ) REFERENCES Product.Suppliers ( SupplierID )
)
COMMENT = 'Formal requests made by the company to suppliers for products or services needed for operations or resale.';
