-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** product
CREATE TABLE IF NOT EXISTS product
(
 CUSS_id number(38,0) NOT NULL,

 CONSTRAINT FK_1 FOREIGN KEY ( CUSS_id ) REFERENCES CUSS ( CUSS_id )
);
