-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** ref_product_storage_mapping
CREATE TABLE IF NOT EXISTS ref_product_storage_mapping
(
 mapping_id           int NOT NULL CONSTRAINT pk_ref_product_storage_mapping PRIMARY KEY,
 product_id           int NOT NULL CONSTRAINT fk_storage_product REFERENCES dim_product,
 storage_condition_id int NOT NULL CONSTRAINT fk_storage_condition REFERENCES ref_storage_conditions (condition_id),
 customer_id          int NOT NULL CONSTRAINT fk_32 REFERENCES CUSTOMERS (CUSTOMER_ID)
);
