-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** ref_product_compliance
CREATE TABLE IF NOT EXISTS ref_product_compliance
(
 compliance_id    int NOT NULL CONSTRAINT pk_ref_product_compliance PRIMARY KEY,
 product_id       int NOT NULL CONSTRAINT fk_34 REFERENCES dim_product,
 standard_id      int NOT NULL CONSTRAINT fk_compliance_standard REFERENCES ref_compliance_standards,
 is_compliant     boolean NOT NULL,
 certification_dt date,
 expiry_dt        date
);
