-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** ref_packaging_types
CREATE TABLE IF NOT EXISTS ref_packaging_types
(
 packaging_id       int NOT NULL CONSTRAINT pk_ref_packaging_types PRIMARY KEY,
 packaging_name     string NOT NULL,
 packaging_material string,
 is_recyclable      boolean NOT NULL,
 is_compostable     boolean NOT NULL,
 cost_per_unit      decimal(10, 4)
);
