-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** ref_compliance_standards
CREATE TABLE IF NOT EXISTS ref_compliance_standards
(
 standard_id    int NOT NULL CONSTRAINT pk_ref_compliance_standards PRIMARY KEY,
 standard_name  string NOT NULL,
 standard_type  string NOT NULL,
 desc           string,
 effective_from date
);
