-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** ref_product_allergens
CREATE TABLE IF NOT EXISTS ref_product_allergens
(
 allergen_id   int NOT NULL CONSTRAINT pk_ref_product_allergens PRIMARY KEY,
 allergen_name string NOT NULL,
 desc          string
);
