-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** ref_storage_conditions
CREATE TABLE IF NOT EXISTS ref_storage_conditions
(
 condition_id    int NOT NULL CONSTRAINT pk_ref_storage_conditions PRIMARY KEY,
 condition_name  string NOT NULL,
 temperature_min decimal(5, 2),
 temperature_max decimal(5, 2),
 humidity_min    decimal(5, 2),
 humidity_max    decimal(5, 2),
 desc            string,
 campaign_id     int NOT NULL COMMENT 'Unique identifier for each marketing campaign.' CONSTRAINT fk_33 REFERENCES CAMPAIGNS (CAMPAIGN_ID),
 new_col         int NOT NULL
);
