-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** ref_distribution_channel
CREATE TABLE IF NOT EXISTS ref_distribution_channel
(
 channel_id   int NOT NULL CONSTRAINT pk_ref_distribution_channel PRIMARY KEY,
 channel_name string NOT NULL,
 channel_type string NOT NULL,
 desc         string
);
