-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "RETAIL_BANKING_CUSTOMERS"."CUSTOMER_IDENTIFICATIONS"
CREATE OR REPLACE TABLE "RETAIL_BANKING_CUSTOMERS"."CUSTOMER_IDENTIFICATIONS"
(
 "IDENTIFICATION_ID"   varchar(100) NOT NULL,
 "CUSTOMER_ID"         varchar(100) NOT NULL,
 "IDENTIFICATION_TYPE" varchar(50),
 "IDENTIFICATION_NM"   varchar(100),
 "ISSUE_DT"            date,
 "EXPIRY_DT"           date,
 "ISSUING_COUNTRY"     varchar(100),
 "CREATED_DT"          timestamp_ntz NOT NULL,
 "FORECAST_TYPE_HKEY"  binary NOT NULL,
 "CHANNEL_HKEY"        binary NOT NULL,
 "DW_CREATED_TS"       datetime NOT NULL,
 "CREATED_BY"          string NOT NULL,
 "UPDTD_TS"            timestamp NOT NULL,
 "UPDTD_BY"            varchar(50) NOT NULL,
 "IS_UPDTD"            boolean NOT NULL,
 "TEST"                timestamp_ntz NOT NULL COMMENT 'test desc',

 CONSTRAINT "pk_CUSTOMER_IDENTIFICATIONS" PRIMARY KEY ( "IDENTIFICATION_ID" ),
 CONSTRAINT "fk_CUSTOMER_IDENTIFICATIONS_CUSTOMERS" FOREIGN KEY ( "CUSTOMER_ID" ) REFERENCES "RETAIL_BANKING_CUSTOMERS"."CUSTOMERS" ( "CUSTOMER_ID" )
);
