-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "RETAIL_BANKING_ACCS"."ACC_TYPES"
CREATE OR REPLACE TABLE "RETAIL_BANKING_ACCS"."ACC_TYPES"
(
 "ACC_TYPE_ID"     varchar(100) NOT NULL COMMENT 'Unique identifier for each account type, serving as the primary key.',
 "TYPE_NAME"       varchar(100) NOT NULL COMMENT 'Name of the account type (e.g., Savings, Checking, Investment).',
 "DESC"            varchar(50) COMMENT 'Detailed description of the account type and its features.',
 "INTEREST_RATE"   decimal(5,2) COMMENT 'Annual interest rate applicable to this account type.',
 "MINIMUM_BALANCE" decimal(12,2) COMMENT 'Minimum balance required to maintain this account type without incurring fees.',
 "DW_CREATED_TS"   datetime NOT NULL,
 "CREATED_BY"      string NOT NULL,
 "UPDTD_TS"        timestamp NOT NULL,
 "UPDTD_BY"        varchar(50) NOT NULL,
 "IS_UPDTD"        boolean NOT NULL,
 "TEST"            timestamp_ntz NOT NULL COMMENT 'test desc',

 CONSTRAINT "pk_ACC_TYPES" PRIMARY KEY ( "ACC_TYPE_ID" )
) WITH TAG ("COST CENTER" = 'finance')
COMMENT = 'Defines various account types available in the retail banking system, including their characteristics and interest rates.';
