-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "RETAIL_BANKING_FEES"."FEES"
CREATE OR REPLACE TABLE "RETAIL_BANKING_FEES"."FEES"
(
 "FEE_ID"        varchar(100) NOT NULL,
 "ACC_ID"        varchar(100) NOT NULL,
 "COL_13"         NOT NULL,
 "FEE_TYPE_ID"   varchar(100) NOT NULL,
 "FEE_AMT"       decimal(8,2) NOT NULL,
 "COL_14"         NOT NULL,
 "FEE_DT"        timestamp_ntz NOT NULL,
 "FEE_STATUS"    varchar(50),
 "DW_CREATED_TS" datetime NOT NULL,
 "CREATED_BY"    string NOT NULL,
 "UPDTD_TS"      timestamp NOT NULL,
 "UPDTD_BY"      varchar(50) NOT NULL,
 "IS_UPDTD"      boolean NOT NULL,
 "TEST"          timestamp_ntz NOT NULL COMMENT 'test desc',
 "LAST_NAME"     varchar(100) NOT NULL COMMENT 'Represents the last name or surname of an individual, providing the family name or inherited name typically shared by members of the same family.',

 CONSTRAINT "pk_FEES" PRIMARY KEY ( "FEE_ID" ),
 CONSTRAINT "fk_FEES_ACCS" FOREIGN KEY ( "ACC_ID", "LAST_NAME" ) REFERENCES "RETAIL_BANKING_ACCS"."ACCS" ( "ACC_ID", "LAST_NAME" ),
 CONSTRAINT "fk_FEES_FEE_TYPES" FOREIGN KEY ( "FEE_TYPE_ID" ) REFERENCES "RETAIL_BANKING_FEES"."FEE_TYPES" ( "FEE_TYPE_ID" )
);
