-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "RETAIL_BANKING_CUSTOMERS"."CUSTOMERS"
CREATE OR REPLACE TABLE "RETAIL_BANKING_CUSTOMERS"."CUSTOMERS"
(
 "CUSTOMER_ID"                    varchar(100) NOT NULL,
 "FIRST_NAME"                     varchar(100) NOT NULL,
 "LAST_NAME"                      varchar(100) NOT NULL,
 "EMAIL"                          varchar(255),
 "PHONE_NM"                       varchar(20),
 "DT_OF_BIRTH"                    date NOT NULL,
 "ADDRESS_LINE1"                  varchar(255),
 "ADDRESS_LINE2"                  varchar(255),
 "CITY"                           varchar(100),
 "STATE"                          varchar(100) COMMENT 'Maximum amount the account can be overdrawn.',
 "POSTAL_CODE"                    varchar(20),
 "COUNTRY"                        varchar(100),
 "CUSTOMER_TYPE"                  varchar(50),
 "REGISTRATION_DT"                timestamp_ntz NOT NULL,
 "CUSTOMER_STATUS"                varchar(50),
 "PREFERRED_COMMUNICATION_METHOD" varchar(50),
 "DW_CREATED_TS"                  datetime NOT NULL,
 "CREATED_BY"                     string NOT NULL,
 "UPDTD_TS"                       timestamp NOT NULL,
 "UPDTD_BY"                       varchar(50) NOT NULL,
 "IS_UPDTD"                       boolean NOT NULL,
 "TEST"                           timestamp_ntz NOT NULL COMMENT 'test desc',

 CONSTRAINT "pk_CUSTOMERS" PRIMARY KEY ( "CUSTOMER_ID" )
) WITH TAG ("COST CENTER" = '');
