-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "RETAIL_BANKING_FRAUD"."FRAUD_ALERTS"
CREATE OR REPLACE TABLE "RETAIL_BANKING_FRAUD"."FRAUD_ALERTS"
(
 "FRAUD_ALERT_ID" varchar(100) NOT NULL,
 "TRANSACTION_ID" varchar(100) NOT NULL,
 "CUSTOMER_ID"    varchar(100) NOT NULL,
 "ALERT_TYPE"     varchar(100),
 "ALERT_DT"       timestamp_ntz NOT NULL,
 "DESC"           text,
 "RISK_SCORE"     integer,
 "STATUS"         varchar(50),
 "DW_CREATED_TS"  datetime NOT NULL,
 "CREATED_BY"     string NOT NULL,
 "UPDTD_TS"       timestamp NOT NULL,
 "UPDTD_BY"       varchar(50) NOT NULL,
 "IS_UPDTD"       boolean NOT NULL,
 "TEST"           timestamp_ntz NOT NULL COMMENT 'test desc',

 CONSTRAINT "pk_FRAUD_ALERTS" PRIMARY KEY ( "FRAUD_ALERT_ID" ),
 CONSTRAINT "fk_FRAUD_ALERTS_CUSTOMERS" FOREIGN KEY ( "CUSTOMER_ID" ) REFERENCES "RETAIL_BANKING_CUSTOMERS"."CUSTOMERS" ( "CUSTOMER_ID" ),
 CONSTRAINT "fk_FRAUD_ALERTS_TRANSACTIONS" FOREIGN KEY ( "TRANSACTION_ID" ) REFERENCES "RETAIL_BANKING_TRANSACTIONS"."TRANSACTIONS" ( "TRANSACTION_ID" )
);
