-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "RETAIL_BANKING_CARDS"."TABLE_25"
CREATE OR REPLACE TABLE "RETAIL_BANKING_CARDS"."TABLE_25"
(
 "DW_CREATED_TS" datetime NOT NULL,
 "CREATED_BY"    string NOT NULL,
 "UPDTD_TS"      timestamp NOT NULL,
 "UPDTD_BY"      varchar(50) NOT NULL,
 "IS_UPDTD"      boolean NOT NULL,
 "TEST"          timestamp_ntz NOT NULL COMMENT 'test desc',
 "CARD_ID"       varchar(100) NOT NULL COMMENT 'Unique identifier for each bank account, serving as the primary key.',

 CONSTRAINT "fk_TABLE_25_CARDS" FOREIGN KEY ( "CARD_ID" ) REFERENCES "RETAIL_BANKING_CARDS"."CARDS" ( "CARD_ID" )
);
