-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "RETAIL_BANKING_TRANSACTIONS"."TRANSACTIONS"
CREATE OR REPLACE TABLE "RETAIL_BANKING_TRANSACTIONS"."TRANSACTIONS"
(
 "TRANSACTION_ID"         varchar(100) NOT NULL COMMENT 'Unique identifier for each banking transaction',
 "ACC_ID"                 varchar(100) NOT NULL COMMENT 'Reference to the specific bank account where the transaction occurred',
 "CARD_ID"                varchar(100) COMMENT 'Optional reference to the payment card used in the transaction',
 "TRANSACTION_TYPE"       varchar(50) COMMENT 'Classification of the transaction (e.g., deposit, withdrawal, transfer)',
 "AMT"                    decimal(12,2) NOT NULL COMMENT 'Monetary value of the transaction in the account''s currency',
 "TRANSACTION_DT"         timestamp_ntz NOT NULL COMMENT 'Date and time when the transaction was processed',
 "DESC"                   text COMMENT 'Detailed narrative or notes about the transaction',
 "MERCHANT_NAME"          varchar(255) COMMENT 'Name of the merchant or business associated with the transaction',
 "MERCHANT_CATEGORY_CODE" varchar(10) COMMENT 'Standard code representing the merchant''s business category',
 "TRANSACTION_STATUS"     varchar(50) COMMENT 'Current state of the transaction (e.g., completed, pending, failed)',
 "DW_CREATED_TS"          datetime NOT NULL COMMENT 'Timestamp of when the transaction record was created in the data warehouse',
 "CREATED_BY"             string NOT NULL COMMENT 'Identifier of the user or system that initiated the transaction record',
 "UPDTD_TS"               timestamp NOT NULL COMMENT 'Timestamp of the most recent update to the transaction record',
 "UPDTD_BY"               varchar(50) NOT NULL COMMENT 'Identifier of the user or system that last modified the transaction record',
 "IS_UPDTD"               boolean NOT NULL COMMENT 'Boolean flag indicating whether the transaction record has been modified',
 "TEST"                   timestamp_ntz NOT NULL COMMENT 'test desc',

 CONSTRAINT "pk_TRANSACTIONS" PRIMARY KEY ( "TRANSACTION_ID" ),
 CONSTRAINT "fk_TRANSACTIONS_CARDS" FOREIGN KEY ( "CARD_ID" ) REFERENCES "RETAIL_BANKING_CARDS"."CARDS" ( "CARD_ID" )
)
COMMENT = 'A comprehensive record of all banking transactions capturing financial activities across customer accounts';
