-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "RETAIL_BANKING_LENDING"."LOANS"
CREATE OR REPLACE TABLE "RETAIL_BANKING_LENDING"."LOANS"
(
 "LOAN_ID"           varchar(100) NOT NULL COMMENT 'Unique identifier for each bank account, serving as the primary key.',
 "CUSTOMER_ID"       varchar(100) NOT NULL COMMENT 'Foreign key referencing the customer who owns this account.',
 "LOAN_TYPE_ID"      varchar(100) NOT NULL COMMENT 'A column named ''first_name'' typically stores the given name or forename of a person. This field usually contains text data representing the individual''s first name in a user, customer, employee, or contact record.',
 "LOAN_AMT"          decimal(15,2) NOT NULL,
 "INTEREST_RATE"     decimal(5,2) NOT NULL,
 "START_DT"          date NOT NULL,
 "END_DT"            date NOT NULL,
 "MONTHLY_PAYMENT"   decimal(12,2) NOT NULL,
 "REMAINING_BALANCE" decimal(15,2) NOT NULL,
 "LOAN_STATUS"       varchar(50),
 "DW_CREATED_TS"     datetime NOT NULL,
 "CREATED_BY"        string NOT NULL,
 "UPDTD_TS"          timestamp NOT NULL,
 "UPDTD_BY"          varchar(50) NOT NULL,
 "IS_UPDTD"          boolean NOT NULL,
 "TEST"              timestamp_ntz NOT NULL COMMENT 'test desc',

 CONSTRAINT "pk_LOANS" PRIMARY KEY ( "LOAN_ID" ),
 CONSTRAINT "fk_LOANS_CUSTOMERS" FOREIGN KEY ( "CUSTOMER_ID" ) REFERENCES "RETAIL_BANKING_CUSTOMERS"."CUSTOMERS" ( "CUSTOMER_ID" ),
 CONSTRAINT "fk_LOANS_LOAN_TYPES" FOREIGN KEY ( "LOAN_TYPE_ID" ) REFERENCES "RETAIL_BANKING_LENDING"."LOAN_TYPES" ( "LOAN_TYPE_ID" )
) WITH TAG ("COST CENTER" = '')
COMMENT = 'Stores individual customer account details, tracking their financial information and account status.';
