-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: test project by hazal.sener+yew@sqldbm.com **

-- ************************************** demo.retail_analytics.sale
CREATE TABLE demo.retail_analytics.sale
(
 sale_id      string NOT NULL CONSTRAINT sale_pk PRIMARY KEY,
 sale_date    date,
 product_id   string CONSTRAINT sale_product_fk REFERENCES demo.retail_analytics.product,
 customer_id  string CONSTRAINT sale_customer_fk REFERENCES demo.retail_analytics.customer,
 store_id     string CONSTRAINT sale_store_fk REFERENCES demo.retail_analytics.store,
 quantity     int,
 total_amount decimal(12,2)
)
USING DELTA
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.feature.appendOnly = 'supported', delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
