-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: test project by hazal.sener+yew@sqldbm.com **

-- ************************************** demo.retail_analytics.product
CREATE TABLE demo.retail_analytics.product
(
 product_id   string NOT NULL CONSTRAINT product_pk PRIMARY KEY,
 product_name string NOT NULL,
 category     string,
 price        decimal(10,2),
 available    boolean
)
USING DELTA
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.feature.appendOnly = 'supported', delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
