-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "RETAIL_BANKING_ACCS"."ACCS"
CREATE OR REPLACE TABLE "RETAIL_BANKING_ACCS"."ACCS"
(
 "ACC_ID"           varchar(100) NOT NULL COMMENT 'Unique identifier for each bank account, serving as the primary key.',
 "LAST_NAME"        varchar(100) NOT NULL COMMENT 'Represents the last name or surname of an individual, providing the family name or inherited name typically shared by members of the same family.',
 "CUSTOMER_ID"      varchar(100) NOT NULL COMMENT 'Foreign key referencing the customer who owns this account.',
 "FIRST_NAME"       varchar(100) NOT NULL COMMENT 'A column named ''first_name'' typically stores the given name or forename of a person. This field usually contains text data representing the individual''s first name in a user, customer, employee, or contact record.',
 "EMAIL"            varchar(255) COMMENT 'Email address for user identification and communication purposes, ensuring unique contact information for each user account.',
 "ACC_TYPE_ID"      varchar(100) NOT NULL COMMENT 'Foreign key referencing the type of account (e.g., Savings, Checking).',
 "ACC_NM"           varchar(50) COMMENT 'External account number used for customer identification and transactions.',
 "CURRENT_BALANCE"  decimal(15,2) NOT NULL COMMENT 'Current available balance in the account.',
 "OPENING_DT"       timestamp_ntz NOT NULL COMMENT 'Date and time when the account was first opened.',
 "LAST_ACTIVITY_DT" timestamp_ntz COMMENT 'Date and time of the most recent transaction or account activity.',
 "ACC_STATUS"       varchar(50) COMMENT 'Current status of the account (e.g., Active, Frozen, Closed).',
 "OVERDRAFT_LIMIT"  decimal(12,2) COMMENT 'Maximum amount the account can be overdrawn.',
 "DW_CREATED_TS"    datetime NOT NULL,
 "CREATED_BY"       string NOT NULL,
 "UPDTD_TS"         timestamp NOT NULL,
 "UPDTD_BY"         varchar(50) NOT NULL,
 "IS_UPDTD"         boolean NOT NULL,
 "TEST"             timestamp_ntz NOT NULL COMMENT 'test desc',
 "CUSTOMER_ID_1"    varchar(100) NOT NULL,

 CONSTRAINT "pk_ACCS" PRIMARY KEY ( "ACC_ID", "LAST_NAME" ),
 CONSTRAINT "fk_ACCS_ACC_TYPES" FOREIGN KEY ( "ACC_TYPE_ID" ) REFERENCES "RETAIL_BANKING_ACCS"."ACC_TYPES" ( "ACC_TYPE_ID" ),
 CONSTRAINT "fk_ACCS_CUSTOMERS" FOREIGN KEY ( "CUSTOMER_ID_1" ) REFERENCES "RETAIL_BANKING_CUSTOMERS"."CUSTOMERS" ( "CUSTOMER_ID" ),
 CONSTRAINT "fk_ACCS_CUSTOMERS_1" FOREIGN KEY ( "CUSTOMER_ID" ) REFERENCES "RETAIL_BANKING_CUSTOMERS"."CUSTOMERS" ( "CUSTOMER_ID" )
) WITH TAG ("COST CENTER" = '')
COMMENT = 'Stores individual customer account details, tracking their financial information and account status.';
