-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "RETAIL_BANKING_FEES"."DIM_FEES"
CREATE OR REPLACE TABLE "RETAIL_BANKING_FEES"."DIM_FEES"
(
 "_HK"           bigint NOT NULL COMMENT 'Deterministic hash key based on customer business keys',
 "EFF_DT"        timestamp_ntz(9) NOT NULL COMMENT 'Start of the recordâ€™s effective period',
 "DW_CREATED_TS" datetime NOT NULL,
 "CREATED_BY"    string NOT NULL,
 "UPDTD_TS"      timestamp NOT NULL,
 "UPDTD_BY"      varchar(50) NOT NULL,
 "IS_UPDTD"      boolean NOT NULL,
 "FEE_ID"        varchar(100) NOT NULL,
 "COL 19"         NOT NULL,
 "ACC_ID"        varchar(100) NOT NULL,
 "FEE_TYPE_ID"   varchar(100) NOT NULL,
 "FEE_AMT"       decimal(8,2) NOT NULL,
 "FEE_DT"        timestamp_ntz NOT NULL,
 "FEE_STATUS"    varchar(50),
 "EXP_DT"        timestamp_ntz(9) NOT NULL DEFAULT 9999-12-31 23:59:59 COMMENT 'End of the recordâ€™s effective period',
 "IS_CURRENT"    boolean NOT NULL DEFAULT Y COMMENT 'Flag for currently active record',
 "LOAD_DTS"      timestamp_ntz(9) NOT NULL COMMENT 'Timestamp when the record was loaded',
 "SOURCE_SYSTEM" varchar(50) DEFAULT unknown COMMENT 'Indicates the application or system where the record originated. Used for traceability and data accountability',
 "TEST"          timestamp_ntz NOT NULL COMMENT 'test desc',

 CONSTRAINT "pk_DIM_FEES" PRIMARY KEY ( "_HK", "EFF_DT" )
)
COMMENT = 'Tracks history using Type 2 methodology with temporal attributes and current flag';
