-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "RETAIL_BANKING_CARDS"."CARDS"
CREATE OR REPLACE TABLE "RETAIL_BANKING_CARDS"."CARDS"
(
 "CARD_ID"        varchar(100) NOT NULL COMMENT 'Unique identifier for each bank account, serving as the primary key.',
 "CUSTOMER_ID"    varchar(100) NOT NULL COMMENT 'Foreign key referencing the customer who owns this account.',
 "CARD_TYPE_ID"   varchar(100) NOT NULL COMMENT 'Foreign key reference to the card type.',
 "CARD_NM"        varchar(16) COMMENT 'Full card number (typically masked in production systems for security).',
 "MASKED_CARD_NM" varchar(16) COMMENT 'Masked representation of the card number showing only last 4 digits for display purposes.',
 "EXPIRY_DT"      date NOT NULL COMMENT 'Date when the card expires and becomes invalid.',
 "CVV"            varchar(4) NOT NULL COMMENT 'Card Verification Value (security code) for transaction authentication.',
 "CARD"           varchar(50) COMMENT 'Current status of the card (e.g., Active, Inactive, Blocked, Expired).',
 "ISSUE_DT"       date NOT NULL COMMENT 'Date when the card was issued to the customer.',
 "DW_CREATED_TS"  datetime NOT NULL,
 "CREATED_BY"     string NOT NULL,
 "UPDTD_TS"       timestamp NOT NULL,
 "UPDTD_BY"       varchar(50) NOT NULL,
 "IS_UPDTD"       boolean NOT NULL,
 "TEST"           timestamp_ntz NOT NULL COMMENT 'test desc',

 CONSTRAINT "pk_CARDS" PRIMARY KEY ( "CARD_ID" ),
 CONSTRAINT "fk_CARDS_CARD_TYPES" FOREIGN KEY ( "CARD_TYPE_ID" ) REFERENCES "RETAIL_BANKING_CARDS"."CARD_TYPES" ( "CARD_TYPE_ID" ),
 CONSTRAINT "fk_CARDS_CUSTOMERS" FOREIGN KEY ( "CUSTOMER_ID" ) REFERENCES "RETAIL_BANKING_CUSTOMERS"."CUSTOMERS" ( "CUSTOMER_ID" )
)
COMMENT = 'Stores individual customer account details, tracking their financial information and account status.';
