-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "RETAIL_BANKING_CUSTOMER_SERVICE"."SUPPORT_TICKETS"
CREATE OR REPLACE TABLE "RETAIL_BANKING_CUSTOMER_SERVICE"."SUPPORT_TICKETS"
(
 "TICKET_ID"      varchar(100) NOT NULL,
 "CUSTOMER_ID"    varchar(100) NOT NULL,
 "TICKET_TYPE"    varchar(100),
 "SUBJECT"        varchar(255) NOT NULL,
 "DESC"           text NOT NULL,
 "PRIORITY"       varchar(50),
 "STATUS"         varchar(50),
 "CREATED_DT"     timestamp_ntz NOT NULL,
 "RESOLVED_DT"    timestamp_ntz,
 "ASSIGNED_AGENT" varchar(100),
 "DW_CREATED_TS"  datetime NOT NULL,
 "CREATED_BY"     string NOT NULL,
 "UPDTD_TS"       timestamp NOT NULL,
 "UPDTD_BY"       varchar(50) NOT NULL,
 "IS_UPDTD"       boolean NOT NULL,
 "TEST"           timestamp_ntz NOT NULL COMMENT 'test desc',

 CONSTRAINT "pk_SUPPORT_TICKETS" PRIMARY KEY ( "TICKET_ID" ),
 CONSTRAINT "fk_SUPPORT_TICKETS_CUSTOMERS" FOREIGN KEY ( "CUSTOMER_ID" ) REFERENCES "RETAIL_BANKING_CUSTOMERS"."CUSTOMERS" ( "CUSTOMER_ID" )
) WITH TAG ("COST CENTER" = '');
