-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "RETAIL_BANKING_CARDS"."CARD_TYPES"
CREATE OR REPLACE TABLE "RETAIL_BANKING_CARDS"."CARD_TYPES"
(
 "CARD_TYPE_ID"  varchar(100) NOT NULL COMMENT 'Unique identifier for the card type.',
 "TYPE_NAME"     varchar(100) NOT NULL COMMENT 'Name of the card type (e.g., Visa, Mastercard, American Express).',
 "DESC"          text COMMENT 'Detailed description of the card type, its features, and benefits.',
 "ANNUAL_FEE"    decimal(8,2) COMMENT 'Annual fee charged for this card type in decimal currency format.',
 "DW_CREATED_TS" datetime NOT NULL,
 "CREATED_BY"    string NOT NULL,
 "UPDTD_TS"      timestamp NOT NULL,
 "UPDTD_BY"      varchar(50) NOT NULL,
 "IS_UPDTD"      boolean NOT NULL,
 "TEST"          timestamp_ntz NOT NULL COMMENT 'test desc',

 CONSTRAINT "pk_CARD_TYPES" PRIMARY KEY ( "CARD_TYPE_ID" )
)
COMMENT = 'Reference table storing card type definitions and their associated fees and characteristics.';
