-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "RETAIL_BANKING_FEES"."FEE_TYPES"
CREATE OR REPLACE TABLE "RETAIL_BANKING_FEES"."FEE_TYPES"
(
 "FEE_TYPE_ID"   varchar(100) NOT NULL,
 "TYPE_NAME"     varchar(100) NOT NULL,
 "DESC"          text,
 "DEFAULT_AMT"   decimal(8,2),
 "DW_CREATED_TS" datetime NOT NULL,
 "CREATED_BY"    string NOT NULL,
 "UPDTD_TS"      timestamp NOT NULL,
 "UPDTD_BY"      varchar(50) NOT NULL,
 "IS_UPDTD"      boolean NOT NULL,
 "TEST"          timestamp_ntz NOT NULL COMMENT 'test desc',

 CONSTRAINT "pk_FEE_TYPES" PRIMARY KEY ( "FEE_TYPE_ID" )
);
