-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** "Sales and Orders".Invoices
CREATE TABLE "Sales and Orders".Invoices
(
 InvoiceID   integer NOT NULL AUTOINCREMENT COMMENT 'A unique identifier for each invoice in the table. This primary key ensures that each invoice record is distinct and can be referenced individually.',
 OrderID     integer COMMENT 'reference to the unique identifier of the sales order associated with the invoice. This foreign key links to the SalesOrders table, allowing the company to associate each invoice with a specific order and track the billing details related to that order.',
 InvoiceDate date COMMENT 'Date when the invoice was issued. This field helps in tracking the timing of billing, managing payment schedules, and monitoring financial records.',
 AmountDue   decimal(10,2) COMMENT 'The total amount of money that is due for payment as stated in the invoice. This includes the cost of products or services provided, taxes, and any other applicable charges. This field is crucial for financial management and tracking outstanding payments.',
 Status      varchar(16777216) COMMENT 'The current status of the invoice, such as "Pending," "Paid," "Overdue," or "Cancelled." This field indicates the payment state of the invoice and helps manage and follow up on outstanding amounts and payment collections.',

 CONSTRAINT PK_Invoices PRIMARY KEY ( InvoiceID ),
 CONSTRAINT FK_Invoices_1 FOREIGN KEY ( OrderID ) REFERENCES "Sales and Orders".SalesOrders ( OrderID )
)
COMMENT = 'The Invoices table records the details of billing statements issued to customers for goods or services provided. Each invoice represents a financial request for payment based on completed sales orders. This table helps track outstanding amounts, manage payment collections, and ensure accurate financial accounting.';
