-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** "Sales and Orders".PaymentDetails
CREATE TABLE "Sales and Orders".PaymentDetails
(
 DetailID        integer NOT NULL AUTOINCREMENT COMMENT 'A unique identifier for each payment detail record in the table. This primary key ensures that each payment detail entry is distinct and can be referenced individually',
 OrderID         integer COMMENT 'A reference to the unique identifier of the sales order associated with the payment details. This foreign key links to the SalesOrders table, allowing the payment details to be connected with a specific order and facilitating tracking of payment information related to each sales transaction.',
 PaymentMethodID integer COMMENT 'A reference to the unique identifier of the payment method used for the order. This foreign key links to the PaymentMethods table, providing information about the type of payment method (e.g., credit card, PayPal) and allowing for detailed tracking of how payments were processed.',
 DetailName      varchar(16777216) COMMENT 'he name or label of the payment detail. This field specifies what the payment detail represents, such as "Credit Card Number," "Bank Account Number," or "Transaction ID." It helps identify the type of information stored in the DetailValue field.',
 DetailValue     varchar(16777216) COMMENT 'he value or actual data associated with the payment detail. This field contains the specific information related to the DetailName, such as the credit card number, bank account details, or other payment-related information. It is used to store and retrieve detailed payment information as required for processing transactions.',

 CONSTRAINT PK_PaymentDetails PRIMARY KEY ( DetailID ),
 CONSTRAINT FK_PaymentDetails_1 FOREIGN KEY ( OrderID ) REFERENCES "Sales and Orders".SalesOrders ( OrderID ),
 CONSTRAINT FK_PaymentDetails_2 FOREIGN KEY ( PaymentMethodID ) REFERENCES "Sales and Orders".PaymentMethods ( PaymentMethodID )
)
COMMENT = 'The PaymentDetails table stores detailed information about the payment methods used for sales orders. This table captures specifics about payment methods, such as credit card numbers or bank account details, and links them to the respective orders and payment methods. It is essential for tracking and managing the financial aspects of transactions';
