-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** "Sales and Orders".SalesOrders
CREATE TABLE IF NOT EXISTS "Sales and Orders".SalesOrders
(
 OrderID     integer NOT NULL AUTOINCREMENT COMMENT 'A unique identifier for each sales order in the table. This primary key ensures that each sales order record is distinct and can be referenced individually. It is typically generated automatically by the system (e.g., an auto-incrementing integer or a UUID).',
 CUSSID      integer COMMENT 'A reference to the unique identifier of the customer who placed the order. This foreign key establishes a link to the Customers table, allowing the company to connect each sales order with the corresponding customer and analyze customer purchasing patterns.',
 CampaignID  integer NOT NULL COMMENT 'A reference to the unique identifier of the marketing campaign associated with the order. This foreign key links to the Campaigns table, helping the company track which sales are influenced by specific marketing efforts, thus measuring the effectiveness of campaigns.',
 OrderDate   date COMMENT 'The date (and optionally the time) when the sales order was placed. This field is essential for tracking sales activity over time, analyzing trends, and managing order processing and fulfillment schedules',
 TotalAmount decimal(10,2) COMMENT 'The total monetary value of the sales order, including all items, taxes, discounts, and any applicable fees. This field is used for financial reporting, revenue analysis, and tracking the financial impact of sales',
 EmployeeID  integer NOT NULL COMMENT 'A reference to the unique identifier of the sales representative who facilitated the order. T',

 CONSTRAINT PK_SalesOrders PRIMARY KEY ( OrderID ),
 CONSTRAINT FK_17 FOREIGN KEY ( CampaignID ) REFERENCES Marketing.Campaigns ( CampaignID ),
 CONSTRAINT FK_CUSSSalesOrders FOREIGN KEY ( CUSSID ) REFERENCES CUSS.CUSS ( CUSSID ) COMMENT 'The Customer Sales Orders relationship connects the Customers table to the SalesOrders table, illustrating the orders placed by customers for purchasing products or services. This is a one-to-many relationship where each customer can have multiple sales orders, but each sales order is associated with only one customer. This relationship captures the purchasing behavior of customers, providing valuable data for sales analysis, order fulfillment, and customer management.

Through this relationship, the company can track customer purchase history, monitor sales performance, and tailor marketing and service efforts to meet customer needs and preferences. It plays a crucial role in understanding customer demand, managing order processing, and enhancing overall customer satisfaction.',
 CONSTRAINT "Sells Order" FOREIGN KEY ( EmployeeID ) REFERENCES "Human Resources".Employee ( EmployeeID )
)
COMMENT = 'Orders placed by customers for purchasing products.
The SalesOrders table captures information about each sales transaction made by customers. It tracks details of orders including which customer made the purchase, any associated marketing campaigns, the sales representative responsible, and financial aspects such as the total amount. This table is essential for managing sales processes, analyzing sales performance, and supporting financial accounting.';
