-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** "Sales and Orders".PaymentMethods
CREATE TABLE IF NOT EXISTS "Sales and Orders".PaymentMethods
(
 PaymentMethodID integer NOT NULL AUTOINCREMENT COMMENT 'A unique identifier for each payment method in the table. This primary key ensures that each payment method record is distinct and can be referenced individually.',
 MethodName      varchar(16777216) COMMENT 'The name of the payment method. This field specifies the type of payment option, such as "Credit Card," "PayPal," "Bank Transfer," or "Cash." It helps users identify and select the appropriate payment method for processing transactions and provides a clear description of the available options.',

 CONSTRAINT PK_PaymentMethods PRIMARY KEY ( PaymentMethodID )
)
COMMENT = 'The PaymentMethods table stores information about the various payment options available for processing transactions. It identifies and categorizes the different methods that customers can use to make payments, such as credit cards, bank transfers, or digital wallets. This table is essential for managing and standardizing the payment options within the system.';
