-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** "Sales and Orders".OrderItems
CREATE TABLE "Sales and Orders".OrderItems
(
 OrderItemID integer NOT NULL AUTOINCREMENT COMMENT 'A unique identifier for each order item record in the table. This primary key ensures that each order item entry is distinct and can be referenced individually.',
 OrderID     integer COMMENT 'A reference to the unique identifier of the sales order to which the item belongs. This foreign key links to the SalesOrders table, associating each order item with its corresponding sales order and enabling tracking of items within specific orders.',
 ProductID   integer COMMENT 'A reference to the unique identifier of the product included in the order item. This foreign key links to the Product table, allowing the company to associate each order item with a specific product and access detailed product information.',
 Quantity    integer COMMENT 'The number of units of the product included in the order item. This field represents the quantity of the product ordered, essential for processing and fulfilling orders, as well as for inventory management and reporting.',
 Price       decimal(10,2) COMMENT 'The price per unit of the product at the time the order was placed. This field reflects the cost of each item as it was sold in the specific order, used for calculating the total order value and managing financial records. It may include any applicable discounts or special pricing',

 CONSTRAINT PK_OrderItems PRIMARY KEY ( OrderItemID ),
 CONSTRAINT FK_OrderItems_1 FOREIGN KEY ( OrderID ) REFERENCES "Sales and Orders".SalesOrders ( OrderID ),
 CONSTRAINT FK_ProductOrderItems FOREIGN KEY ( ProductID ) REFERENCES Product.Products ( ProductID )
)
COMMENT = 'Specific products included in a sales order.';
