-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Awesome Project by hazal.sener@sqldbm.com ***

-- ************************************** Sample_Table
CREATE TABLE Sample_Table
(
 "Sample Column"  NOT NULL,
 ETL_ID          timestamp NOT NULL COMMENT 'Table load date',
 ETL_TIMESTAMP   timestamp_ntz NOT NULL COMMENT 'Table load date TIME',

 CONSTRAINT PK_1_Sample_Table PRIMARY KEY ( "Sample Column" ),
 CONSTRAINT FK_Danny_Table_Sample_Table FOREIGN KEY (  ) REFERENCES Danny_Table (  )
);
