-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Awesome Project by hazal.sener@sqldbm.com ***

-- ************************************** Sampel_GTable
CREATE TABLE Sampel_GTable
(
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date',
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME',
 Sample_Column varchar(50) NOT NULL,

 CONSTRAINT PK_1_Sampel_GTable PRIMARY KEY ( Sample_Column )
);
