-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: test project by hazal.sener+yew@sqldbm.com **

-- ************************************** demo.serge.customer
CREATE TABLE demo.serge.customer
(
 id           int,
 name         string,
 email        varchar(50),
 prefernce    string,
 age          int,
 balance      decimal(10,2),
 tags         array<string>,
 address      struct<street:string,city:string,zip:string>,
 preferences  array<struct<type:string,value:string>>,
 preferences2 array<struct<key:string,value:string>>
)
USING DELTA
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.feature.appendOnly = 'supported', delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
