-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** silver_customers
CREATE TABLE IF NOT EXISTS silver_customers
(
 customer_id        string NOT NULL COMMENT 'Unique identifier for each customer' CONSTRAINT pk_35 PRIMARY KEY,
 fname              string NOT NULL COMMENT 'Customer''s first name',
 lname              string NOT NULL COMMENT 'Customer''s last name',
 email              string COMMENT 'Customer''s email address',
 phone_num          string COMMENT 'Customer''s phone number',
 registration_dt    timestamp COMMENT 'Customer registration date',
 data_quality_score decimal(5,2) COMMENT 'Data quality score after cleansing'
)
 COMMENT 'Cleansed and validated customer data from raw staging tables';
