-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** silver_products
CREATE TABLE IF NOT EXISTS silver_products
(
 total_amt          string NOT NULL CONSTRAINT pk_37 PRIMARY KEY,
 product_name       string NOT NULL COMMENT 'Product name',
 category_id        string COMMENT 'Product category identifier',
 stock_quantity     int NOT NULL COMMENT 'Current stock quantity',
 unit_prc           decimal(10,2) NOT NULL COMMENT 'Unit price',
 desc               string COMMENT 'Product description',
 data_quality_score decimal(5,2) COMMENT 'Data quality score after cleansing'
);
