-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** silver_sales
CREATE TABLE IF NOT EXISTS silver_sales
(
 sale_id            string NOT NULL COMMENT 'Unique identifier for each sale' CONSTRAINT pk_34 PRIMARY KEY,
 customer_id        string COMMENT 'Identifier of the customer who made the purchase' CONSTRAINT fk_37 REFERENCES silver_customers,
 total_amt_1        string NOT NULL COMMENT 'Identifier of the product sold' CONSTRAINT fk_38 REFERENCES silver_products (total_amt),
 sale_dt            timestamp NOT NULL COMMENT 'Date and time of the sale',
 quantity           int NOT NULL COMMENT 'Number of products sold',
 total_amt          decimal(10,2) NOT NULL COMMENT 'Total sale amount',
 data_quality_score decimal(5,2) COMMENT 'Data quality score after cleansing'
)
 COMMENT 'Cleansed and validated sales data from raw staging tables';
