-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** silver_inventory
CREATE TABLE IF NOT EXISTS silver_inventory
(
 inventory_id       string NOT NULL COMMENT 'Unique identifier for each inventory record' CONSTRAINT pk_36 PRIMARY KEY,
 total_amt          string NOT NULL COMMENT 'Product identifier' CONSTRAINT fk_39 REFERENCES silver_products,
 location_id        string NOT NULL COMMENT 'Store or warehouse location identifier',
 available_quantity int NOT NULL COMMENT 'Available quantity at location',
 last_updtd         timestamp NOT NULL COMMENT 'Date and time of inventory update',
 discnt_amt         decimal(5,2)
)
 COMMENT 'Cleansed and validated inventory data from raw staging tables';
