-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** silver_suppliers
CREATE TABLE IF NOT EXISTS silver_suppliers
(
 supplier_id        string NOT NULL COMMENT 'Unique identifier for each supplier',
 company_name       string NOT NULL COMMENT 'Supplier company name',
 contact_name       string COMMENT 'Supplier contact person',
 email              string COMMENT 'Supplier email address',
 phone_num          string COMMENT 'Supplier phone number',
 registration_dt    timestamp COMMENT 'Date supplier was added to the system',
 data_quality_score decimal(5,2) COMMENT 'Data quality score after cleansing'
)
 COMMENT 'Cleansed and validated supplier data from raw staging tables';
