-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Project - Snowflake by hazal.sener@sqldbm.com *

-- ************************************** sqldbm_31
CREATE TABLE sqldbm_31
(
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date',
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME'
);
