-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample Project - Snowflake by hazal.sener@sqldbm.com *

-- ************************************** sqldbm_table_w_warning
CREATE TABLE sqldbm_table_w_warning
(

);
