-- ****************************************** SqlDBM: Snowflake ******************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model', V1 by hazal.sener+yew@sqldbm.com *

-- ************************************** supplier
CREATE TABLE supplier
(
 supplier_id number(38,0) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( supplier_id )
);
