-- **************************************** SqlDBM: Databricks ****************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer - team copy by hazal.sener+yew@sqldbm.com *

-- ************************************** table_24
CREATE TABLE table_24
(
)
 TBLPROPERTIES (delta.columnMapping.mode = 'name');
