-- ************************* SqlDBM: Databricks *************************
-- ******* Generated by SqlDBM: ha-1 by hazal.sener+yew@sqldbm.com ******

-- ************************************** table_45
CREATE TABLE IF NOT EXISTS table_45
(
 dw_created_ts           timestamp NOT NULL,
 created_by              varchar NOT NULL,
 created_dt              date NOT NULL,
 etl_id                  timestamp NOT NULL,
 agg_id                  int NOT NULL CONSTRAINT fk_34_1 REFERENCES agg_daily_sales,
 product_id              int NOT NULL,
 store                   int NOT NULL,
 employee_id             int,
 quantity_produced       decimal(12, 4) NOT NULL,
 planned_quantity        decimal(12, 4) NOT NULL,
 raw_material_cost       decimal(15, 4) NOT NULL,
 labor_cost              decimal(15, 4) NOT NULL,
 production_time_minutes int,
 quality_score           decimal(3, 2)
)
 TBLPROPERTIES (delta.columnMapping.mode = 'name');
