-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Sample: Retail Banking by hazal.sener+yew@sqldbm.com *

-- ************************************** "TABLE_15"
CREATE OR REPLACE TABLE "TABLE_15"
(
 "DW_CREATED_TS" datetime NOT NULL,
 "CREATED_BY"    string NOT NULL,
 "UPDTD_TS"      timestamp NOT NULL,
 "UPDTD_BY"      varchar(50) NOT NULL,
 "IS_UPDTD"      boolean NOT NULL,
 "TEST"          timestamp_ntz NOT NULL COMMENT 'test desc',
 "ACC_ID"        varchar(36) NOT NULL,
 "FEE_TYPE_ID"   varchar(36) NOT NULL,
 "FEE_AMT"       decimal(8,2) NOT NULL,
 "FEE_DT"        timestamp_ntz NOT NULL,
 "FEE_STATUS"    varchar(50)
);
